packages:
  - examples/typescript
  - examples/react-viewer
  - packages/app-support
  - packages/sdk-typescript
  - packages/tool-drawing
  - packages/tool-scraper
  - packages/tool-support
  - packages/ui
  - packages/viewer
