/**
 * Mastercam's schema, as the exporter reads it.
 *
 * **Generated. Do not edit.** `pnpm mastercam:adopt` writes this from
 * `mastercam/digest.json`, and `tests/export-mastercam-schema.test.ts` fails
 * when the two disagree — so a hand edit here survives until the next test run.
 *
 * Mastercam 28.230, schema version 32.
 */

import type { Row, TableSpec } from './sqlite/index.js'

/** Every table a `.TOOLDB` declares, in the order `sqlite_master` records them. */
export const MASTERCAM_TABLES: readonly TableSpec[] = [
  {
    name: 'TlAccessory',
    sql: 'CREATE TABLE [TlAccessory](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlAccessory_1] PRIMARY KEY NOT NULL REFERENCES TlAssemblyItem([ID]) DEFERRABLE INITIALLY DEFERRED)',
    columns: [{ name: 'ID', type: 'GUID' }],
    indexes: [{ name: 'sqlite_autoindex_TlAccessory_1', columns: ['ID'] }],
  },
  {
    name: 'TlAccessoryCollection',
    sql: 'CREATE TABLE [TlAccessoryCollection](\r\n    [ID] GUID NOT NULL, \r\n    [TlAccessoryID] GUID NOT NULL REFERENCES TlAccessory([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    CONSTRAINT [sqlite_autoindex_TlAccessoryCollection_1] PRIMARY KEY([ID], [TlAccessoryID]))',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'TlAccessoryID', type: 'GUID' },
    ],
    indexes: [
      { name: 'sqlite_autoindex_TlAccessoryCollection_1', columns: ['ID', 'TlAccessoryID'] },
    ],
  },
  {
    name: 'TlAdaptiveItem',
    sql: 'CREATE TABLE [TlAdaptiveItem](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlAdaptiveItem_1] PRIMARY KEY NOT NULL REFERENCES TlAdaptiveItem([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [IsExtension] BOOL)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'IsExtension', type: 'BOOL' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlAdaptiveItem_1', columns: ['ID'] }],
  },
  {
    name: 'TlAssembly',
    sql: 'CREATE TABLE [TlAssembly](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlAssembly_1] PRIMARY KEY, \r\n    [Name] VARCHAR, \r\n    [Description] VARCHAR, \r\n    [MainHolder] GUID REFERENCES TlHolder([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [MainTool] GUID REFERENCES TlTool([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [ToolNumber] INT, \r\n    [MachineGroup] INT, \r\n    [RelationshipHierarchyXML] VARCHAR, \r\n    [DiameterOffsetNum] INT, \r\n    [LengthOffsetNum] INT, \r\n    [MaxRamp] DOUBLE, \r\n    [IsMetric] BOOL, \r\n    [TlGraphicsFileCollectionID] GUID REFERENCES TlGraphicsFileCollection([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [TlAccessoryCollectionID] GUID REFERENCES TlAccessoryCollection([ID]) DEFERRABLE INITIALLY DEFERRED,\r\n    [ExternalId] VARCHAR)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'Name', type: 'VARCHAR' },
      { name: 'Description', type: 'VARCHAR' },
      { name: 'MainHolder', type: 'GUID' },
      { name: 'MainTool', type: 'GUID' },
      { name: 'ToolNumber', type: 'INT' },
      { name: 'MachineGroup', type: 'INT' },
      { name: 'RelationshipHierarchyXML', type: 'VARCHAR' },
      { name: 'DiameterOffsetNum', type: 'INT' },
      { name: 'LengthOffsetNum', type: 'INT' },
      { name: 'MaxRamp', type: 'DOUBLE' },
      { name: 'IsMetric', type: 'BOOL' },
      { name: 'TlGraphicsFileCollectionID', type: 'GUID' },
      { name: 'TlAccessoryCollectionID', type: 'GUID' },
      { name: 'ExternalId', type: 'VARCHAR' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlAssembly_1', columns: ['ID'] }],
  },
  {
    name: 'TlAssemblyAdaptiveItem',
    sql: 'CREATE TABLE [TlAssemblyAdaptiveItem](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlAssemblyAdaptiveItem_1] PRIMARY KEY NOT NULL REFERENCES TlAssemblyComponentNew([ID]) DEFERRABLE INITIALLY DEFERRED)',
    columns: [{ name: 'ID', type: 'GUID' }],
    indexes: [{ name: 'sqlite_autoindex_TlAssemblyAdaptiveItem_1', columns: ['ID'] }],
  },
  {
    name: 'TlAssemblyComponent',
    sql: 'CREATE TABLE [TlAssemblyComponent](\r\n    [TlAssemblyID] GUID REFERENCES TlAssembly([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [TlAssemblyItemID] GUID REFERENCES TlAssemblyItem([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [ParentID] GUID REFERENCES TlAssemblyItem([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [MTransformID] GUID REFERENCES TlMatrix4x4([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [UTransformID] GUID REFERENCES TlMatrix4x4([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [CTransformID] GUID REFERENCES TlMatrix4x4([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [CScalar] FLOAT, \r\n    CONSTRAINT [sqlite_autoindex_TlAssemblyComponent_1] PRIMARY KEY([TlAssemblyID], [TlAssemblyItemID]))',
    columns: [
      { name: 'TlAssemblyID', type: 'GUID' },
      { name: 'TlAssemblyItemID', type: 'GUID' },
      { name: 'ParentID', type: 'GUID' },
      { name: 'MTransformID', type: 'GUID' },
      { name: 'UTransformID', type: 'GUID' },
      { name: 'CTransformID', type: 'GUID' },
      { name: 'CScalar', type: 'FLOAT' },
    ],
    indexes: [
      {
        name: 'sqlite_autoindex_TlAssemblyComponent_1',
        columns: ['TlAssemblyID', 'TlAssemblyItemID'],
      },
    ],
  },
  {
    name: 'TlAssemblyComponentNew',
    sql: 'CREATE TABLE [TlAssemblyComponentNew](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlAssemblyComponentNew_1] PRIMARY KEY, \r\n    [ItemID] GUID REFERENCES TlAssemblyItem([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [ParentID] GUID REFERENCES TlAssemblyComponentNew([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [ParentConnectionID] GUID REFERENCES TlConnection([ID]) DEFERRABLE INITIALLY DEFERRED)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'ItemID', type: 'GUID' },
      { name: 'ParentID', type: 'GUID' },
      { name: 'ParentConnectionID', type: 'GUID' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlAssemblyComponentNew_1', columns: ['ID'] }],
  },
  {
    name: 'TlAssemblyComponentTree',
    sql: 'CREATE TABLE [TlAssemblyComponentTree](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlAssemblyComponentTree_1] PRIMARY KEY, \r\n    [RootID] GUID REFERENCES TlAssemblyComponentNew([TlAssemblyID]) DEFERRABLE INITIALLY DEFERRED)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'RootID', type: 'GUID' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlAssemblyComponentTree_1', columns: ['ID'] }],
  },
  {
    name: 'TlAssemblyConfiguration',
    sql: 'CREATE TABLE [TlAssemblyConfiguration](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlAssemblyConfiguration_1] PRIMARY KEY, \r\n    [ToolAssemblyID] GUID, \r\n    [Name] VARCHAR, \r\n    [Description] VARCHAR)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'ToolAssemblyID', type: 'GUID' },
      { name: 'Name', type: 'VARCHAR' },
      { name: 'Description', type: 'VARCHAR' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlAssemblyConfiguration_1', columns: ['ID'] }],
  },
  {
    name: 'TlAssemblyInsert',
    sql: 'CREATE TABLE [TlAssemblyInsert](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlAssemblyInsert_1] PRIMARY KEY NOT NULL REFERENCES TlAssemblyComponentNew([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [CutPlaneLocatorID] GUID REFERENCES TlLocator([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [BoundaryGenParamsID] GUID REFERENCES TlBoundaryGenerationParams([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [CutProfileID] GUID REFERENCES TlProfile([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [NonCutProfileID] GUID REFERENCES TlProfile([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [CuttingSide] INT, \r\n    [ActiveSpindle] INT, \r\n    [IsInsertUp] BOOL, \r\n    [IsInverted] BOOL,\r\n    [IsInsertFront] BOOL)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'CutPlaneLocatorID', type: 'GUID' },
      { name: 'BoundaryGenParamsID', type: 'GUID' },
      { name: 'CutProfileID', type: 'GUID' },
      { name: 'NonCutProfileID', type: 'GUID' },
      { name: 'CuttingSide', type: 'INT' },
      { name: 'ActiveSpindle', type: 'INT' },
      { name: 'IsInsertUp', type: 'BOOL' },
      { name: 'IsInverted', type: 'BOOL' },
      { name: 'IsInsertFront', type: 'BOOL' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlAssemblyInsert_1', columns: ['ID'] }],
  },
  {
    name: 'TlAssemblyItem',
    sql: 'CREATE TABLE [TlAssemblyItem](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlAssemblyItem_1] PRIMARY KEY, \r\n    [CatalogID] VARCHAR, \r\n    [GeometryFile] VARCHAR, \r\n    [IsMetric] BOOL, \r\n    [Location] VARCHAR, \r\n    [TlToolMaterialID] GUID REFERENCES TlToolMaterial([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [TlToolTypeID] GUID REFERENCES TlToolType([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [TlManufacturerID] GUID REFERENCES TlManufacturer([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [Name] VARCHAR, \r\n    [Description] VARCHAR, \r\n    [Quantity] INT, \r\n    [ThruCoolant] BOOL, \r\n    [IsCatalogItem] BOOL, \r\n    [GaugeLength] DOUBLE, \r\n    [GaugeDiameter] DOUBLE, \r\n    [TlGraphicsFileCollectionID] GUID REFERENCES TlGraphicsFileCollection([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [ModelFileID] GUID REFERENCES TlGraphicsFile([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [MachineSideConnectionID] GUID REFERENCES TlConnection([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [WorkpieceSideConnectionMapID] GUID REFERENCES TlConnectionMap([ID]) DEFERRABLE INITIALLY DEFERRED,\r\n    [MachineSideProjectionAdjustment] DOUBLE,\r\n    [IsProjectionAdjustmentEditable] BOOL)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'CatalogID', type: 'VARCHAR' },
      { name: 'GeometryFile', type: 'VARCHAR' },
      { name: 'IsMetric', type: 'BOOL' },
      { name: 'Location', type: 'VARCHAR' },
      { name: 'TlToolMaterialID', type: 'GUID' },
      { name: 'TlToolTypeID', type: 'GUID' },
      { name: 'TlManufacturerID', type: 'GUID' },
      { name: 'Name', type: 'VARCHAR' },
      { name: 'Description', type: 'VARCHAR' },
      { name: 'Quantity', type: 'INT' },
      { name: 'ThruCoolant', type: 'BOOL' },
      { name: 'IsCatalogItem', type: 'BOOL' },
      { name: 'GaugeLength', type: 'DOUBLE' },
      { name: 'GaugeDiameter', type: 'DOUBLE' },
      { name: 'TlGraphicsFileCollectionID', type: 'GUID' },
      { name: 'ModelFileID', type: 'GUID' },
      { name: 'MachineSideConnectionID', type: 'GUID' },
      { name: 'WorkpieceSideConnectionMapID', type: 'GUID' },
      { name: 'MachineSideProjectionAdjustment', type: 'DOUBLE' },
      { name: 'IsProjectionAdjustmentEditable', type: 'BOOL' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlAssemblyItem_1', columns: ['ID'] }],
  },
  {
    name: 'TlAssemblyTurnHolder',
    sql: 'CREATE TABLE [TlAssemblyTurnHolder](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlAssemblyTurnHolder_1] PRIMARY KEY NOT NULL REFERENCES TlAssemblyComponentNew([ID]) DEFERRABLE INITIALLY DEFERRED)',
    columns: [{ name: 'ID', type: 'GUID' }],
    indexes: [{ name: 'sqlite_autoindex_TlAssemblyTurnHolder_1', columns: ['ID'] }],
  },
  {
    name: 'TlAuxData',
    sql: 'CREATE TABLE [TlAuxData](\r\n    [ID] GUID NOT NULL, \r\n    [Class] VARCHAR, \r\n    [Version] INT, \r\n    [Tag] VARCHAR, \r\n    [Data] BLOB, \r\n    CONSTRAINT [sqlite_autoindex_TlAuxData_1] PRIMARY KEY([ID], [Class], [Tag]))',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'Class', type: 'VARCHAR' },
      { name: 'Version', type: 'INT' },
      { name: 'Tag', type: 'VARCHAR' },
      { name: 'Data', type: 'BLOB' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlAuxData_1', columns: ['ID', 'Class', 'Tag'] }],
  },
  {
    name: 'TlBoundaryGenerationParams',
    sql: 'CREATE TABLE [TlBoundaryGenerationParams](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlBoundaryGenerationParams_1] PRIMARY KEY, \r\n    [Method] INT, \r\n    [PlaneOffset1] DOUBLE, \r\n    [PlaneOffset2] DOUBLE, \r\n    [PlaneSense1] BOOL, \r\n    [CalcTol] DOUBLE, \r\n    [CalcHolderTol] DOUBLE)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'Method', type: 'INT' },
      { name: 'PlaneOffset1', type: 'DOUBLE' },
      { name: 'PlaneOffset2', type: 'DOUBLE' },
      { name: 'PlaneSense1', type: 'BOOL' },
      { name: 'CalcTol', type: 'DOUBLE' },
      { name: 'CalcHolderTol', type: 'DOUBLE' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlBoundaryGenerationParams_1', columns: ['ID'] }],
  },
  {
    name: 'TlConnection',
    sql: 'CREATE TABLE [TlConnection](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlConnection_1] PRIMARY KEY, \r\n    [Type] VARCHAR, \r\n    [Size] VARCHAR, \r\n    [LocatorID] GUID NOT NULL REFERENCES TlLocator([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [IsRound] BOOL, \r\n    [Thickness] DOUBLE, \r\n    [Width] DOUBLE, \r\n    [Name] VARCHAR)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'Type', type: 'VARCHAR' },
      { name: 'Size', type: 'VARCHAR' },
      { name: 'LocatorID', type: 'GUID' },
      { name: 'IsRound', type: 'BOOL' },
      { name: 'Thickness', type: 'DOUBLE' },
      { name: 'Width', type: 'DOUBLE' },
      { name: 'Name', type: 'VARCHAR' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlConnection_1', columns: ['ID'] }],
  },
  {
    name: 'TlConnectionMap',
    sql: 'CREATE TABLE [TlConnectionMap](\r\n    [ID] GUID NOT NULL, \r\n    [TlConnectionID] GUID NOT NULL REFERENCES TlConnection([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    CONSTRAINT [sqlite_autoindex_TlConnectionMap_1] PRIMARY KEY([ID], [TlConnectionID]))',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'TlConnectionID', type: 'GUID' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlConnectionMap_1', columns: ['ID', 'TlConnectionID'] }],
  },
  {
    name: 'TlCoolant',
    sql: 'CREATE TABLE [TlCoolant](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlCoolant_1] PRIMARY KEY, \r\n    [OldStyle] INT, \r\n    [Flood] INT, \r\n    [FloodPos] INT, \r\n    [Mist] INT, \r\n    [MistPos] INT, \r\n    [Tool] INT, \r\n    [ToolPos] INT, \r\n    [Custom1] INT, \r\n    [Custom1Pos] INT, \r\n    [Custom2] INT, \r\n    [Custom2Pos] INT, \r\n    [Custom3] INT, \r\n    [Custom3Pos] INT, \r\n    [Custom4] INT, \r\n    [Custom4Pos] INT, \r\n    [Custom5] INT, \r\n    [Custom5Pos] INT, \r\n    [Custom6] INT, \r\n    [Custom6Pos] INT, \r\n    [Custom7] INT, \r\n    [Custom7Pos] INT)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'OldStyle', type: 'INT' },
      { name: 'Flood', type: 'INT' },
      { name: 'FloodPos', type: 'INT' },
      { name: 'Mist', type: 'INT' },
      { name: 'MistPos', type: 'INT' },
      { name: 'Tool', type: 'INT' },
      { name: 'ToolPos', type: 'INT' },
      { name: 'Custom1', type: 'INT' },
      { name: 'Custom1Pos', type: 'INT' },
      { name: 'Custom2', type: 'INT' },
      { name: 'Custom2Pos', type: 'INT' },
      { name: 'Custom3', type: 'INT' },
      { name: 'Custom3Pos', type: 'INT' },
      { name: 'Custom4', type: 'INT' },
      { name: 'Custom4Pos', type: 'INT' },
      { name: 'Custom5', type: 'INT' },
      { name: 'Custom5Pos', type: 'INT' },
      { name: 'Custom6', type: 'INT' },
      { name: 'Custom6Pos', type: 'INT' },
      { name: 'Custom7', type: 'INT' },
      { name: 'Custom7Pos', type: 'INT' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlCoolant_1', columns: ['ID'] }],
  },
  {
    name: 'TlCutParam',
    sql: 'CREATE TABLE [TlCutParam](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlCutParam_1] PRIMARY KEY, \r\n    [TlToolGradeID] GUID REFERENCES TlToolGrade([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [TlToolTypeID] GUID REFERENCES TlToolType([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [TlOpTypeID] GUID REFERENCES TlOpType([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [TlManufacturerID] GUID REFERENCES TlManufacturer([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [Name] VARCHAR, \r\n    [Description] VARCHAR, \r\n    [MinDiameter] DOUBLE, \r\n    [MaxDiameter] DOUBLE, \r\n    [CutSpeed] DOUBLE, \r\n    [FPT] DOUBLE, \r\n    [SurfaceFinish] DOUBLE, \r\n    [RoughRadialDoC] DOUBLE, \r\n    [RoughAxialDoC] DOUBLE, \r\n    [FinishRadialDoC] DOUBLE, \r\n    [FinishAxialDoC] DOUBLE, \r\n    [ToolLifeLinear] DOUBLE, \r\n    [ToolLifeMinutes] DOUBLE, \r\n    [IsMetric] BOOL, \r\n    [TlCutQuality] INT, \r\n    [TlWorkMaterialID] GUID REFERENCES TlWorkMaterial([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [TlCutSource] INT, \r\n    [IsProven] BOOL, \r\n    [TlFeedFactor] INT, \r\n    [MinFPT] DOUBLE, \r\n    [MaxFPT] DOUBLE, \r\n    [MinCutSpeed] DOUBLE, \r\n    [MaxCutSpeed] DOUBLE, \r\n    [MachineName] VARCHAR)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'TlToolGradeID', type: 'GUID' },
      { name: 'TlToolTypeID', type: 'GUID' },
      { name: 'TlOpTypeID', type: 'GUID' },
      { name: 'TlManufacturerID', type: 'GUID' },
      { name: 'Name', type: 'VARCHAR' },
      { name: 'Description', type: 'VARCHAR' },
      { name: 'MinDiameter', type: 'DOUBLE' },
      { name: 'MaxDiameter', type: 'DOUBLE' },
      { name: 'CutSpeed', type: 'DOUBLE' },
      { name: 'FPT', type: 'DOUBLE' },
      { name: 'SurfaceFinish', type: 'DOUBLE' },
      { name: 'RoughRadialDoC', type: 'DOUBLE' },
      { name: 'RoughAxialDoC', type: 'DOUBLE' },
      { name: 'FinishRadialDoC', type: 'DOUBLE' },
      { name: 'FinishAxialDoC', type: 'DOUBLE' },
      { name: 'ToolLifeLinear', type: 'DOUBLE' },
      { name: 'ToolLifeMinutes', type: 'DOUBLE' },
      { name: 'IsMetric', type: 'BOOL' },
      { name: 'TlCutQuality', type: 'INT' },
      { name: 'TlWorkMaterialID', type: 'GUID' },
      { name: 'TlCutSource', type: 'INT' },
      { name: 'IsProven', type: 'BOOL' },
      { name: 'TlFeedFactor', type: 'INT' },
      { name: 'MinFPT', type: 'DOUBLE' },
      { name: 'MaxFPT', type: 'DOUBLE' },
      { name: 'MinCutSpeed', type: 'DOUBLE' },
      { name: 'MaxCutSpeed', type: 'DOUBLE' },
      { name: 'MachineName', type: 'VARCHAR' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlCutParam_1', columns: ['ID'] }],
  },
  {
    name: 'TlCuttingConfiguration',
    sql: 'CREATE TABLE [TlCuttingConfiguration](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlCuttingConfiguration_1] PRIMARY KEY NOT NULL REFERENCES TlAssemblyConfiguration([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [CoolantID] GUID NOT NULL REFERENCES TlCoolant([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [IndexMaterial] INT, \r\n    [FeedRate] DOUBLE, \r\n    [FeedRateUnits] INT, \r\n    [PlungeRate] DOUBLE, \r\n    [PlungeRateUnits] INT, \r\n    [SpindleSpeed] INT, \r\n    [SpindleSpeedUnits] INT, \r\n    [MaterialSFMAdjust] DOUBLE, \r\n    [MaterialFPTAdjust] DOUBLE)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'CoolantID', type: 'GUID' },
      { name: 'IndexMaterial', type: 'INT' },
      { name: 'FeedRate', type: 'DOUBLE' },
      { name: 'FeedRateUnits', type: 'INT' },
      { name: 'PlungeRate', type: 'DOUBLE' },
      { name: 'PlungeRateUnits', type: 'INT' },
      { name: 'SpindleSpeed', type: 'INT' },
      { name: 'SpindleSpeedUnits', type: 'INT' },
      { name: 'MaterialSFMAdjust', type: 'DOUBLE' },
      { name: 'MaterialFPTAdjust', type: 'DOUBLE' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlCuttingConfiguration_1', columns: ['ID'] }],
  },
  {
    name: 'TlCuttingConfigurationGrooving',
    sql: 'CREATE TABLE [TlCuttingConfigurationGrooving](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlCuttingConfigurationGrooving_1] PRIMARY KEY NOT NULL REFERENCES TlCuttingConfiguration([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [StockClearance] DOUBLE, \r\n    [BackoffPercent] DOUBLE, \r\n    [RoughDepthOfCut] DOUBLE, \r\n    [FinishDepthOfCut] DOUBLE)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'StockClearance', type: 'DOUBLE' },
      { name: 'BackoffPercent', type: 'DOUBLE' },
      { name: 'RoughDepthOfCut', type: 'DOUBLE' },
      { name: 'FinishDepthOfCut', type: 'DOUBLE' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlCuttingConfigurationGrooving_1', columns: ['ID'] }],
  },
  {
    name: 'TlCuttingConfigurationThreading',
    sql: 'CREATE TABLE [TlCuttingConfigurationThreading](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlCuttingConfigurationThreading_1] PRIMARY KEY NOT NULL REFERENCES TlCuttingConfiguration([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [FirstDepthOfCut] DOUBLE, \r\n    [LastDepthOfCut] DOUBLE, \r\n    [FinishPassAllowance] DOUBLE, \r\n    [PullOff] DOUBLE, \r\n    [NumSpringCuts] INT, \r\n    [MinThreadPitch] DOUBLE, \r\n    [MaxThreadPitch] DOUBLE)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'FirstDepthOfCut', type: 'DOUBLE' },
      { name: 'LastDepthOfCut', type: 'DOUBLE' },
      { name: 'FinishPassAllowance', type: 'DOUBLE' },
      { name: 'PullOff', type: 'DOUBLE' },
      { name: 'NumSpringCuts', type: 'INT' },
      { name: 'MinThreadPitch', type: 'DOUBLE' },
      { name: 'MaxThreadPitch', type: 'DOUBLE' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlCuttingConfigurationThreading_1', columns: ['ID'] }],
  },
  {
    name: 'TlCuttingConfigurationTurningBoring',
    sql: 'CREATE TABLE [TlCuttingConfigurationTurningBoring](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlCuttingConfigurationTurningBoring_1] PRIMARY KEY NOT NULL REFERENCES TlCuttingConfiguration([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [RoughDepthOfCut] DOUBLE, \r\n    [FinishDepthOfCut] DOUBLE, \r\n    [RoughOverlapAmount] DOUBLE, \r\n    [FacingRetractionAmount] DOUBLE, \r\n    [FacingXOvercutAmount] DOUBLE)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'RoughDepthOfCut', type: 'DOUBLE' },
      { name: 'FinishDepthOfCut', type: 'DOUBLE' },
      { name: 'RoughOverlapAmount', type: 'DOUBLE' },
      { name: 'FacingRetractionAmount', type: 'DOUBLE' },
      { name: 'FacingXOvercutAmount', type: 'DOUBLE' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlCuttingConfigurationTurningBoring_1', columns: ['ID'] }],
  },
  {
    name: 'TlGraphicsFile',
    sql: 'CREATE TABLE [TlGraphicsFile](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlGraphicsFile_1] PRIMARY KEY NOT NULL, \r\n    [FileDataSize] INT, \r\n    [FileData] BLOB, \r\n    [FileFormat] INT)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'FileDataSize', type: 'INT' },
      { name: 'FileData', type: 'BLOB' },
      { name: 'FileFormat', type: 'INT' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlGraphicsFile_1', columns: ['ID'] }],
  },
  {
    name: 'TlGraphicsFileCollection',
    sql: 'CREATE TABLE [TlGraphicsFileCollection](\r\n    [ID] GUID NOT NULL, \r\n    [TlGraphicsFileID] GUID NOT NULL REFERENCES TlGraphicsFile([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    CONSTRAINT [sqlite_autoindex_TlGraphicsFileCollection_1] PRIMARY KEY([ID], [TlGraphicsFileID]))',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'TlGraphicsFileID', type: 'GUID' },
    ],
    indexes: [
      { name: 'sqlite_autoindex_TlGraphicsFileCollection_1', columns: ['ID', 'TlGraphicsFileID'] },
    ],
  },
  {
    name: 'TlHolder',
    sql: 'CREATE TABLE [TlHolder](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlHolder_1] PRIMARY KEY REFERENCES TlAssemblyItem([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [LibraryName] VARCHAR, \r\n    [HolderType] INT, \r\n    [UpperConnectionType] INT, \r\n    [UpperConnectionSize] VARCHAR, \r\n    [LowerConnectionType] INT, \r\n    [LowerConnectionSize] VARCHAR, \r\n    [CustomDisplayType] INT, \r\n    [TlAccessoryCollectionID] GUID REFERENCES TlAccessoryCollection([ID]) DEFERRABLE INITIALLY DEFERRED)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'LibraryName', type: 'VARCHAR' },
      { name: 'HolderType', type: 'INT' },
      { name: 'UpperConnectionType', type: 'INT' },
      { name: 'UpperConnectionSize', type: 'VARCHAR' },
      { name: 'LowerConnectionType', type: 'INT' },
      { name: 'LowerConnectionSize', type: 'VARCHAR' },
      { name: 'CustomDisplayType', type: 'INT' },
      { name: 'TlAccessoryCollectionID', type: 'GUID' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlHolder_1', columns: ['ID'] }],
  },
  {
    name: 'TlHolderAssembly',
    sql: 'CREATE TABLE [TlHolderAssembly](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlHolderAssembly_1] PRIMARY KEY, \r\n    [Name] VARCHAR, \r\n    [Description] VARCHAR,\r\n    [TlAssemblyComponentTreeID] GUID REFERENCES TlAssemblyComponentTree([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [ImageID] GUID REFERENCES TlGraphicsFile([ID]) DEFERRABLE INITIALLY DEFERRED,\r\n    [IsMetric] BOOL)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'Name', type: 'VARCHAR' },
      { name: 'Description', type: 'VARCHAR' },
      { name: 'TlAssemblyComponentTreeID', type: 'GUID' },
      { name: 'ImageID', type: 'GUID' },
      { name: 'IsMetric', type: 'BOOL' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlHolderAssembly_1', columns: ['ID'] }],
  },
  {
    name: 'TlHolderLathe',
    sql: 'CREATE TABLE [TlHolderLathe](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlHolderLathe_1] PRIMARY KEY NOT NULL REFERENCES TlAssemblyItem([ID]), \r\n    [Class] VARCHAR, \r\n    [Version] INT, \r\n    [Tag] VARCHAR, \r\n    [AnsiShapeCode] VARCHAR, \r\n    [Type] INT, \r\n    [InsertShapes] VARCHAR, \r\n    [Length] FLOAT, \r\n    [Width] FLOAT, \r\n    [ShankWidth] FLOAT, \r\n    [ShankHeight] FLOAT, \r\n    [HeadLength] FLOAT, \r\n    [HeadWidth] FLOAT, \r\n    [ChamferWidth] FLOAT, \r\n    [ChamferHeight] FLOAT, \r\n    [EndCuttingEdgeAngle] FLOAT, \r\n    [SideCuttingEdgeAngle] FLOAT, \r\n    [RoundShank] BOOL, \r\n    [LeftHandTool] BOOL, \r\n    [IsCustom] BOOL,\r\n    [VerticallyMountedTool] BOOL)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'Class', type: 'VARCHAR' },
      { name: 'Version', type: 'INT' },
      { name: 'Tag', type: 'VARCHAR' },
      { name: 'AnsiShapeCode', type: 'VARCHAR' },
      { name: 'Type', type: 'INT' },
      { name: 'InsertShapes', type: 'VARCHAR' },
      { name: 'Length', type: 'FLOAT' },
      { name: 'Width', type: 'FLOAT' },
      { name: 'ShankWidth', type: 'FLOAT' },
      { name: 'ShankHeight', type: 'FLOAT' },
      { name: 'HeadLength', type: 'FLOAT' },
      { name: 'HeadWidth', type: 'FLOAT' },
      { name: 'ChamferWidth', type: 'FLOAT' },
      { name: 'ChamferHeight', type: 'FLOAT' },
      { name: 'EndCuttingEdgeAngle', type: 'FLOAT' },
      { name: 'SideCuttingEdgeAngle', type: 'FLOAT' },
      { name: 'RoundShank', type: 'BOOL' },
      { name: 'LeftHandTool', type: 'BOOL' },
      { name: 'IsCustom', type: 'BOOL' },
      { name: 'VerticallyMountedTool', type: 'BOOL' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlHolderLathe_1', columns: ['ID'] }],
  },
  {
    name: 'TlHolderLatheBoring',
    sql: 'CREATE TABLE [TlHolderLatheBoring](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlHolderLatheBoring_1] PRIMARY KEY NOT NULL REFERENCES TlHolderLathe([ID]))',
    columns: [{ name: 'ID', type: 'GUID' }],
    indexes: [{ name: 'sqlite_autoindex_TlHolderLatheBoring_1', columns: ['ID'] }],
  },
  {
    name: 'TlHolderLatheDrill',
    sql: 'CREATE TABLE [TlHolderLatheDrill](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlHolderLatheDrill_1] PRIMARY KEY NOT NULL REFERENCES TlHolderLathe([ID]))',
    columns: [{ name: 'ID', type: 'GUID' }],
    indexes: [{ name: 'sqlite_autoindex_TlHolderLatheDrill_1', columns: ['ID'] }],
  },
  {
    name: 'TlHolderLatheGrooving',
    sql: 'CREATE TABLE [TlHolderLatheGrooving](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlHolderLatheGrooving_1] PRIMARY KEY NOT NULL REFERENCES TlHolderLathe([ID]))',
    columns: [{ name: 'ID', type: 'GUID' }],
    indexes: [{ name: 'sqlite_autoindex_TlHolderLatheGrooving_1', columns: ['ID'] }],
  },
  {
    name: 'TlHolderLatheLiveCenter',
    sql: 'CREATE TABLE [TlHolderLatheLiveCenter](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlHolderLatheLiveCenter_1] PRIMARY KEY NOT NULL REFERENCES TlHolderLathe([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [PointStyle] INT, \r\n    [CompressionLength] DOUBLE, \r\n    [MaxWorkpieceWeight] DOUBLE, \r\n    [MaxRPM] INT, \r\n    [TaperStyle] INT, \r\n    [TaperSize] DOUBLE)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'PointStyle', type: 'INT' },
      { name: 'CompressionLength', type: 'DOUBLE' },
      { name: 'MaxWorkpieceWeight', type: 'DOUBLE' },
      { name: 'MaxRPM', type: 'INT' },
      { name: 'TaperStyle', type: 'INT' },
      { name: 'TaperSize', type: 'DOUBLE' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlHolderLatheLiveCenter_1', columns: ['ID'] }],
  },
  {
    name: 'TlHolderLatheThreading',
    sql: 'CREATE TABLE [TlHolderLatheThreading](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlHolderLatheThreading_1] PRIMARY KEY NOT NULL REFERENCES TlHolderLathe([ID]))',
    columns: [{ name: 'ID', type: 'GUID' }],
    indexes: [{ name: 'sqlite_autoindex_TlHolderLatheThreading_1', columns: ['ID'] }],
  },
  {
    name: 'TlHolderLatheTurning',
    sql: 'CREATE TABLE [TlHolderLatheTurning](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlHolderLatheTurning_1] PRIMARY KEY NOT NULL REFERENCES TlHolderLathe([ID]))',
    columns: [{ name: 'ID', type: 'GUID' }],
    indexes: [{ name: 'sqlite_autoindex_TlHolderLatheTurning_1', columns: ['ID'] }],
  },
  {
    name: 'TlHolemakingOpParams',
    sql: 'CREATE TABLE [TlHolemakingOpParams](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlHolemakingOpParams_1] PRIMARY KEY NOT NULL REFERENCES TlOpParams([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [CannedCycleType] INT, \r\n    [Peck1] DOUBLE, \r\n    [Peck2] DOUBLE, \r\n    [PeckClear] DOUBLE, \r\n    [ChipBreak] DOUBLE, \r\n    [Dwell] DOUBLE)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'CannedCycleType', type: 'INT' },
      { name: 'Peck1', type: 'DOUBLE' },
      { name: 'Peck2', type: 'DOUBLE' },
      { name: 'PeckClear', type: 'DOUBLE' },
      { name: 'ChipBreak', type: 'DOUBLE' },
      { name: 'Dwell', type: 'DOUBLE' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlHolemakingOpParams_1', columns: ['ID'] }],
  },
  {
    name: 'TlInsert',
    sql: 'CREATE TABLE [TlInsert](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlInsert_1] PRIMARY KEY NOT NULL REFERENCES TlAssemblyItem([ID]), \r\n    [AnsiShapeCode] VARCHAR, \r\n    [ICDiameter] FLOAT, \r\n    [Length] FLOAT, \r\n    [Width] FLOAT, \r\n    [CornerRadius] FLOAT, \r\n    [Thickness] FLOAT, \r\n    [TlGradeID] GUID REFERENCES TlToolGrade([ID]), \r\n    [IsCustom] BOOL, \r\n    [Is3d] BOOL, \r\n    [CuttingSide] INT)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'AnsiShapeCode', type: 'VARCHAR' },
      { name: 'ICDiameter', type: 'FLOAT' },
      { name: 'Length', type: 'FLOAT' },
      { name: 'Width', type: 'FLOAT' },
      { name: 'CornerRadius', type: 'FLOAT' },
      { name: 'Thickness', type: 'FLOAT' },
      { name: 'TlGradeID', type: 'GUID' },
      { name: 'IsCustom', type: 'BOOL' },
      { name: 'Is3d', type: 'BOOL' },
      { name: 'CuttingSide', type: 'INT' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlInsert_1', columns: ['ID'] }],
  },
  {
    name: 'TlInsertGrooving',
    sql: 'CREATE TABLE [TlInsertGrooving](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlInsertGrooving_1] PRIMARY KEY NOT NULL REFERENCES TlInsert([ID]), \r\n    [CutLength] FLOAT, \r\n    [ShankWidth] FLOAT, \r\n    [EndLength] FLOAT, \r\n    [NotchPointLocation] FLOAT, \r\n    [EndAngle] FLOAT, \r\n    [RoughDepthOfCut] FLOAT, \r\n    [FinishDepthOfCut] FLOAT, \r\n    [StockClearance] FLOAT, \r\n    [BackoffPercent] FLOAT)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'CutLength', type: 'FLOAT' },
      { name: 'ShankWidth', type: 'FLOAT' },
      { name: 'EndLength', type: 'FLOAT' },
      { name: 'NotchPointLocation', type: 'FLOAT' },
      { name: 'EndAngle', type: 'FLOAT' },
      { name: 'RoughDepthOfCut', type: 'FLOAT' },
      { name: 'FinishDepthOfCut', type: 'FLOAT' },
      { name: 'StockClearance', type: 'FLOAT' },
      { name: 'BackoffPercent', type: 'FLOAT' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlInsertGrooving_1', columns: ['ID'] }],
  },
  {
    name: 'TlInsertLatheDrill',
    sql: 'CREATE TABLE [TlInsertLatheDrill](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlInsertLatheDrill_1] PRIMARY KEY NOT NULL REFERENCES TlInsert([ID]), \r\n    [DrillType] SMALLINT, \r\n    [Diameter] FLOAT, \r\n    [ShankDiameter] FLOAT, \r\n    [TipAngle] FLOAT, \r\n    [FluteLength] FLOAT, \r\n    [CutLength] FLOAT, \r\n    [FluteAngle] FLOAT, \r\n    [FluteCount] INT, \r\n    [ChamferHeight] FLOAT, \r\n    [TipDiameter] FLOAT, \r\n    [TipLength] FLOAT, \r\n    [ShoulderLength] FLOAT, \r\n    [Pitch] FLOAT, \r\n    [TapType] SMALLINT, \r\n    [Peck1] FLOAT, \r\n    [Peck2] FLOAT, \r\n    [PeckClr] FLOAT, \r\n    [Retract] FLOAT, \r\n    [DwellTime] FLOAT, \r\n    [Cycle] INT)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'DrillType', type: 'SMALLINT' },
      { name: 'Diameter', type: 'FLOAT' },
      { name: 'ShankDiameter', type: 'FLOAT' },
      { name: 'TipAngle', type: 'FLOAT' },
      { name: 'FluteLength', type: 'FLOAT' },
      { name: 'CutLength', type: 'FLOAT' },
      { name: 'FluteAngle', type: 'FLOAT' },
      { name: 'FluteCount', type: 'INT' },
      { name: 'ChamferHeight', type: 'FLOAT' },
      { name: 'TipDiameter', type: 'FLOAT' },
      { name: 'TipLength', type: 'FLOAT' },
      { name: 'ShoulderLength', type: 'FLOAT' },
      { name: 'Pitch', type: 'FLOAT' },
      { name: 'TapType', type: 'SMALLINT' },
      { name: 'Peck1', type: 'FLOAT' },
      { name: 'Peck2', type: 'FLOAT' },
      { name: 'PeckClr', type: 'FLOAT' },
      { name: 'Retract', type: 'FLOAT' },
      { name: 'DwellTime', type: 'FLOAT' },
      { name: 'Cycle', type: 'INT' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlInsertLatheDrill_1', columns: ['ID'] }],
  },
  {
    name: 'TlInsertThreading',
    sql: 'CREATE TABLE [TlInsertThreading](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlInsertThreading_1] PRIMARY KEY NOT NULL REFERENCES TlInsert([ID]), \r\n    [InsertStyle] INT, \r\n    [ThreadType] INT, \r\n    [IsExternalThread] BOOL, \r\n    [MinThreadPitch] DOUBLE, \r\n    [MaxThreadPitch] DOUBLE, \r\n    [NotchPointLocation] DOUBLE, \r\n    [LaydownHeight] DOUBLE, \r\n    [FlatWidth] DOUBLE, \r\n    [FirstDepthOfCut] DOUBLE, \r\n    [LastDepthOfCut] DOUBLE, \r\n    [FinishAllowance] DOUBLE, \r\n    [Pulloff] DOUBLE, \r\n    [SpringCuts] INT)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'InsertStyle', type: 'INT' },
      { name: 'ThreadType', type: 'INT' },
      { name: 'IsExternalThread', type: 'BOOL' },
      { name: 'MinThreadPitch', type: 'DOUBLE' },
      { name: 'MaxThreadPitch', type: 'DOUBLE' },
      { name: 'NotchPointLocation', type: 'DOUBLE' },
      { name: 'LaydownHeight', type: 'DOUBLE' },
      { name: 'FlatWidth', type: 'DOUBLE' },
      { name: 'FirstDepthOfCut', type: 'DOUBLE' },
      { name: 'LastDepthOfCut', type: 'DOUBLE' },
      { name: 'FinishAllowance', type: 'DOUBLE' },
      { name: 'Pulloff', type: 'DOUBLE' },
      { name: 'SpringCuts', type: 'INT' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlInsertThreading_1', columns: ['ID'] }],
  },
  {
    name: 'TlInsertTurningBoring',
    sql: 'CREATE TABLE [TlInsertTurningBoring](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlInsertTurningBoring_1] PRIMARY KEY NOT NULL REFERENCES TlInsert([ID]), \r\n    [AnsiCrossSectionCode] VARCHAR, \r\n    [ReliefAngle] FLOAT, \r\n    [RoughDepthOfCut] FLOAT, \r\n    [FinishDepthOfCut] FLOAT, \r\n    [RoughOverlap] FLOAT, \r\n    [FacingRetract] FLOAT, \r\n    [FacingXOvercut] FLOAT, \r\n    [Definition] INT, \r\n    [IsMultiDirectional] BOOL)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'AnsiCrossSectionCode', type: 'VARCHAR' },
      { name: 'ReliefAngle', type: 'FLOAT' },
      { name: 'RoughDepthOfCut', type: 'FLOAT' },
      { name: 'FinishDepthOfCut', type: 'FLOAT' },
      { name: 'RoughOverlap', type: 'FLOAT' },
      { name: 'FacingRetract', type: 'FLOAT' },
      { name: 'FacingXOvercut', type: 'FLOAT' },
      { name: 'Definition', type: 'INT' },
      { name: 'IsMultiDirectional', type: 'BOOL' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlInsertTurningBoring_1', columns: ['ID'] }],
  },
  {
    name: 'TlLatheDefinition',
    sql: 'CREATE TABLE [TlLatheDefinition](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlLatheDefinition_1] PRIMARY KEY NOT NULL REFERENCES TlAssemblyConfiguration([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [DefinitionIndex] INT, \r\n    [ToolOffset] INT, \r\n    [ToolBackOffset] INT, \r\n    [HomePositionX] DOUBLE, \r\n    [HomePositionZ] DOUBLE, \r\n    [IsFeedDirReversed] BOOL, \r\n    [CompPointXlateX] DOUBLE, \r\n    [CompPointXlateY] DOUBLE, \r\n    [CompMethod] INT, \r\n    [CompQuadrant] INT, \r\n    [CompRadius] DOUBLE, \r\n    [ClearanceSideAngle] DOUBLE, \r\n    [ClearanceEndAngle] DOUBLE, \r\n    [ClearanceWidth] DOUBLE, \r\n    [ClearanceHeight] DOUBLE, \r\n    [AssemblyInsertID] GUID REFERENCES TlAssemblyInsert([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [CuttingConfigurationID] GUID REFERENCES TlCuttingConfiguration([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [ToolImageID] GUID REFERENCES TlGraphicsFile([ID]) DEFERRABLE INITIALLY DEFERRED)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'DefinitionIndex', type: 'INT' },
      { name: 'ToolOffset', type: 'INT' },
      { name: 'ToolBackOffset', type: 'INT' },
      { name: 'HomePositionX', type: 'DOUBLE' },
      { name: 'HomePositionZ', type: 'DOUBLE' },
      { name: 'IsFeedDirReversed', type: 'BOOL' },
      { name: 'CompPointXlateX', type: 'DOUBLE' },
      { name: 'CompPointXlateY', type: 'DOUBLE' },
      { name: 'CompMethod', type: 'INT' },
      { name: 'CompQuadrant', type: 'INT' },
      { name: 'CompRadius', type: 'DOUBLE' },
      { name: 'ClearanceSideAngle', type: 'DOUBLE' },
      { name: 'ClearanceEndAngle', type: 'DOUBLE' },
      { name: 'ClearanceWidth', type: 'DOUBLE' },
      { name: 'ClearanceHeight', type: 'DOUBLE' },
      { name: 'AssemblyInsertID', type: 'GUID' },
      { name: 'CuttingConfigurationID', type: 'GUID' },
      { name: 'ToolImageID', type: 'GUID' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlLatheDefinition_1', columns: ['ID'] }],
  },
  {
    name: 'TlLocator',
    sql: 'CREATE TABLE [TlLocator](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlLocator_1] PRIMARY KEY NOT NULL, \r\n    [IsMetric] BOOL, \r\n    [r00] FLOAT, \r\n    [r01] FLOAT, \r\n    [r02] FLOAT, \r\n    [r10] FLOAT, \r\n    [r11] FLOAT, \r\n    [r12] FLOAT, \r\n    [r20] FLOAT, \r\n    [r21] FLOAT, \r\n    [r22] FLOAT, \r\n    [t0] FLOAT, \r\n    [t1] FLOAT, \r\n    [t2] FLOAT)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'IsMetric', type: 'BOOL' },
      { name: 'r00', type: 'FLOAT' },
      { name: 'r01', type: 'FLOAT' },
      { name: 'r02', type: 'FLOAT' },
      { name: 'r10', type: 'FLOAT' },
      { name: 'r11', type: 'FLOAT' },
      { name: 'r12', type: 'FLOAT' },
      { name: 'r20', type: 'FLOAT' },
      { name: 'r21', type: 'FLOAT' },
      { name: 'r22', type: 'FLOAT' },
      { name: 't0', type: 'FLOAT' },
      { name: 't1', type: 'FLOAT' },
      { name: 't2', type: 'FLOAT' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlLocator_1', columns: ['ID'] }],
  },
  {
    name: 'TlManufacturer',
    sql: 'CREATE TABLE [TlManufacturer](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlManufacturer_1] PRIMARY KEY, \r\n    [Name] VARCHAR, \r\n    [Description] VARCHAR)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'Name', type: 'VARCHAR' },
      { name: 'Description', type: 'VARCHAR' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlManufacturer_1', columns: ['ID'] }],
  },
  {
    name: 'TlMaterial',
    sql: 'CREATE TABLE [TlMaterial](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlMaterial_1] PRIMARY KEY, \r\n    [Name] VARCHAR, \r\n    [Description] VARCHAR)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'Name', type: 'VARCHAR' },
      { name: 'Description', type: 'VARCHAR' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlMaterial_1', columns: ['ID'] }],
  },
  {
    name: 'TlMatrix4x4',
    sql: 'CREATE TABLE [TlMatrix4x4](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlMatrix4x4_1] PRIMARY KEY, \r\n    [m00] FLOAT, \r\n    [m01] FLOAT, \r\n    [m02] FLOAT, \r\n    [m03] FLOAT, \r\n    [m10] FLOAT, \r\n    [m11] FLOAT, \r\n    [m12] FLOAT, \r\n    [m13] FLOAT, \r\n    [m20] FLOAT, \r\n    [m21] FLOAT, \r\n    [m22] FLOAT, \r\n    [m23] FLOAT, \r\n    [m30] FLOAT, \r\n    [m31] FLOAT, \r\n    [m32] FLOAT, \r\n    [m33] FLOAT)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'm00', type: 'FLOAT' },
      { name: 'm01', type: 'FLOAT' },
      { name: 'm02', type: 'FLOAT' },
      { name: 'm03', type: 'FLOAT' },
      { name: 'm10', type: 'FLOAT' },
      { name: 'm11', type: 'FLOAT' },
      { name: 'm12', type: 'FLOAT' },
      { name: 'm13', type: 'FLOAT' },
      { name: 'm20', type: 'FLOAT' },
      { name: 'm21', type: 'FLOAT' },
      { name: 'm22', type: 'FLOAT' },
      { name: 'm23', type: 'FLOAT' },
      { name: 'm30', type: 'FLOAT' },
      { name: 'm31', type: 'FLOAT' },
      { name: 'm32', type: 'FLOAT' },
      { name: 'm33', type: 'FLOAT' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlMatrix4x4_1', columns: ['ID'] }],
  },
  {
    name: 'TlMillingOpParams',
    sql: 'CREATE TABLE [TlMillingOpParams](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlMillingOpParams_1] PRIMARY KEY NOT NULL REFERENCES TlOpParams([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [IsRough] BOOL, \r\n    [IsFinish] BOOL, \r\n    [StepoverRoughXY] DOUBLE, \r\n    [StepoverRoughZ] DOUBLE, \r\n    [StepoverFinishXY] DOUBLE, \r\n    [StepoverFinishZ] DOUBLE)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'IsRough', type: 'BOOL' },
      { name: 'IsFinish', type: 'BOOL' },
      { name: 'StepoverRoughXY', type: 'DOUBLE' },
      { name: 'StepoverRoughZ', type: 'DOUBLE' },
      { name: 'StepoverFinishXY', type: 'DOUBLE' },
      { name: 'StepoverFinishZ', type: 'DOUBLE' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlMillingOpParams_1', columns: ['ID'] }],
  },
  {
    name: 'TlOpGroup',
    sql: 'CREATE TABLE [TlOpGroup](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlOpGroup_1] PRIMARY KEY, \r\n    [Name] VARCHAR, \r\n    [Description] VARCHAR, \r\n    [ImagePath] VARCHAR, \r\n    [Image] BLOB)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'Name', type: 'VARCHAR' },
      { name: 'Description', type: 'VARCHAR' },
      { name: 'ImagePath', type: 'VARCHAR' },
      { name: 'Image', type: 'BLOB' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlOpGroup_1', columns: ['ID'] }],
  },
  {
    name: 'TlOpParams',
    sql: 'CREATE TABLE [TlOpParams](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlOpParams_1] PRIMARY KEY NOT NULL, \r\n    [MaterialSFMAdjust] DOUBLE, \r\n    [MaterialFPTAdjust] DOUBLE, \r\n    [FeedRate] DOUBLE, \r\n    [RetractRate] DOUBLE, \r\n    [SpindleSpeed] INT, \r\n    [PlungeRate] DOUBLE, \r\n    [TlCoolantID] GUID REFERENCES TlCoolant([ID]), \r\n    [IsMetric] BOOL)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'MaterialSFMAdjust', type: 'DOUBLE' },
      { name: 'MaterialFPTAdjust', type: 'DOUBLE' },
      { name: 'FeedRate', type: 'DOUBLE' },
      { name: 'RetractRate', type: 'DOUBLE' },
      { name: 'SpindleSpeed', type: 'INT' },
      { name: 'PlungeRate', type: 'DOUBLE' },
      { name: 'TlCoolantID', type: 'GUID' },
      { name: 'IsMetric', type: 'BOOL' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlOpParams_1', columns: ['ID'] }],
  },
  {
    name: 'TlOpType',
    sql: 'CREATE TABLE [TlOpType](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlOpType_1] PRIMARY KEY, \r\n    [TlOpGroupID] GUID REFERENCES TlOpGroup([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [Name] VARCHAR, \r\n    [Description] VARCHAR)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'TlOpGroupID', type: 'GUID' },
      { name: 'Name', type: 'VARCHAR' },
      { name: 'Description', type: 'VARCHAR' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlOpType_1', columns: ['ID'] }],
  },
  {
    name: 'TlProfile',
    sql: 'CREATE TABLE [TlProfile](\r\n    [ID] GUID NOT NULL, \r\n    [TlProfileSegmentID] GUID NOT NULL REFERENCES TlProfileSegment([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    CONSTRAINT [sqlite_autoindex_TlProfile_1] PRIMARY KEY([ID], [TlProfileSegmentID]))',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'TlProfileSegmentID', type: 'GUID' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlProfile_1', columns: ['ID', 'TlProfileSegmentID'] }],
  },
  {
    name: 'TlProfileArcSegment',
    sql: 'CREATE TABLE [TlProfileArcSegment](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlProfileArcSegment_1] PRIMARY KEY NOT NULL REFERENCES TlProfileSegment([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [CenterX] DOUBLE, \r\n    [CenterY] DOUBLE, \r\n    [Radius] DOUBLE, \r\n    [StartAngle] DOUBLE, \r\n    [SweepAngle] DOUBLE)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'CenterX', type: 'DOUBLE' },
      { name: 'CenterY', type: 'DOUBLE' },
      { name: 'Radius', type: 'DOUBLE' },
      { name: 'StartAngle', type: 'DOUBLE' },
      { name: 'SweepAngle', type: 'DOUBLE' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlProfileArcSegment_1', columns: ['ID'] }],
  },
  {
    name: 'TlProfileData',
    sql: 'CREATE TABLE [TlProfileData](\r\n    [ItemID] GUID REFERENCES TlAssemblyItem([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [Segment] INT, \r\n    [Type] INT, \r\n    [Color] INT, \r\n    [x0] DOUBLE, \r\n    [y0] DOUBLE, \r\n    [x1] DOUBLE, \r\n    [y1] DOUBLE, \r\n    [radius] DOUBLE, \r\n    [StartAngle] DOUBLE, \r\n    [SweepAngle] DOUBLE, \r\n    CONSTRAINT [sqlite_autoindex_TlProfileData_1] PRIMARY KEY([ItemID], [Segment]))',
    columns: [
      { name: 'ItemID', type: 'GUID' },
      { name: 'Segment', type: 'INT' },
      { name: 'Type', type: 'INT' },
      { name: 'Color', type: 'INT' },
      { name: 'x0', type: 'DOUBLE' },
      { name: 'y0', type: 'DOUBLE' },
      { name: 'x1', type: 'DOUBLE' },
      { name: 'y1', type: 'DOUBLE' },
      { name: 'radius', type: 'DOUBLE' },
      { name: 'StartAngle', type: 'DOUBLE' },
      { name: 'SweepAngle', type: 'DOUBLE' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlProfileData_1', columns: ['ItemID', 'Segment'] }],
  },
  {
    name: 'TlProfileLineSegment',
    sql: 'CREATE TABLE [TlProfileLineSegment](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlProfileLineSegment_1] PRIMARY KEY NOT NULL REFERENCES TlProfileSegment([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [x0] DOUBLE, \r\n    [y0] DOUBLE, \r\n    [x1] DOUBLE, \r\n    [y1] DOUBLE)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'x0', type: 'DOUBLE' },
      { name: 'y0', type: 'DOUBLE' },
      { name: 'x1', type: 'DOUBLE' },
      { name: 'y1', type: 'DOUBLE' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlProfileLineSegment_1', columns: ['ID'] }],
  },
  {
    name: 'TlProfileSegment',
    sql: 'CREATE TABLE [TlProfileSegment](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlProfileSegment_1] PRIMARY KEY NOT NULL, \r\n    [Color] INT)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'Color', type: 'INT' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlProfileSegment_1', columns: ['ID'] }],
  },
  {
    name: 'TlRelations',
    sql: 'CREATE TABLE [TlRelations](\r\n    [ParentID] GUID REFERENCES TlAssemblyItem([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [ChildID] GUID, \r\n    CONSTRAINT [sqlite_autoindex_TlRelations_1] PRIMARY KEY([ParentID], [ChildID]))',
    columns: [
      { name: 'ParentID', type: 'GUID' },
      { name: 'ChildID', type: 'GUID' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlRelations_1', columns: ['ParentID', 'ChildID'] }],
  },
  {
    name: 'TlTool',
    sql: 'CREATE TABLE [TlTool](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlTool_1] PRIMARY KEY NOT NULL REFERENCES TlAssemblyItem([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [OpToolInfo] BLOB, \r\n    [ToolNumber] INT, \r\n    [ToolStation] INT, \r\n    [IsCustom] BOOL, \r\n    [CustomDisplayType] INT, \r\n    [TlAccessoryCollectionID] GUID REFERENCES TlAccessoryCollection([ID]) DEFERRABLE INITIALLY DEFERRED)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'OpToolInfo', type: 'BLOB' },
      { name: 'ToolNumber', type: 'INT' },
      { name: 'ToolStation', type: 'INT' },
      { name: 'IsCustom', type: 'BOOL' },
      { name: 'CustomDisplayType', type: 'INT' },
      { name: 'TlAccessoryCollectionID', type: 'GUID' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlTool_1', columns: ['ID'] }],
  },
  {
    name: 'TlToolAssembly',
    sql: 'CREATE TABLE [TlToolAssembly](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlToolAssembly_1] PRIMARY KEY, \r\n    [Name] VARCHAR, \r\n    [Description] VARCHAR, \r\n    [IsMetric] BOOL, \r\n    [Type] INT, \r\n    [ToolNumber] INT, \r\n    [ToolStation] INT, \r\n    [IsVertical] BOOL, \r\n    [IsInverted] BOOL, \r\n    [ToolAngle] DOUBLE, \r\n    [ActiveTurret] INT, \r\n    [RequiresToolLocator] BOOL, \r\n    [TlAssemblyComponentTreeID] GUID REFERENCES TlAssemblyComponentTree([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [TlAccessoryCollectionID] GUID REFERENCES TlAccessoryCollection([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [TlGraphicsFileCollectionID] GUID REFERENCES TlGraphicsFileCollection([ID]) DEFERRABLE INITIALLY DEFERRED, ExternalId VARCHAR)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'Name', type: 'VARCHAR' },
      { name: 'Description', type: 'VARCHAR' },
      { name: 'IsMetric', type: 'BOOL' },
      { name: 'Type', type: 'INT' },
      { name: 'ToolNumber', type: 'INT' },
      { name: 'ToolStation', type: 'INT' },
      { name: 'IsVertical', type: 'BOOL' },
      { name: 'IsInverted', type: 'BOOL' },
      { name: 'ToolAngle', type: 'DOUBLE' },
      { name: 'ActiveTurret', type: 'INT' },
      { name: 'RequiresToolLocator', type: 'BOOL' },
      { name: 'TlAssemblyComponentTreeID', type: 'GUID' },
      { name: 'TlAccessoryCollectionID', type: 'GUID' },
      { name: 'TlGraphicsFileCollectionID', type: 'GUID' },
      { name: 'ExternalId', type: 'VARCHAR' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlToolAssembly_1', columns: ['ID'] }],
  },
  {
    name: 'TlToolBarrelMill',
    sql: 'CREATE TABLE [TlToolBarrelMill](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlToolBarrelMill_1] PRIMARY KEY REFERENCES TlToolMill([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [BarrelLength] DOUBLE, \r\n    [ProfileRadius] DOUBLE, \r\n    [PrimaryCornerRadius] DOUBLE, \r\n    [UpperRadius] DOUBLE, \r\n    [TaperAngle] DOUBLE, \r\n    [TipDiameter] DOUBLE)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'BarrelLength', type: 'DOUBLE' },
      { name: 'ProfileRadius', type: 'DOUBLE' },
      { name: 'PrimaryCornerRadius', type: 'DOUBLE' },
      { name: 'UpperRadius', type: 'DOUBLE' },
      { name: 'TaperAngle', type: 'DOUBLE' },
      { name: 'TipDiameter', type: 'DOUBLE' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlToolBarrelMill_1', columns: ['ID'] }],
  },
  {
    name: 'TlToolBoring',
    sql: 'CREATE TABLE [TlToolBoring](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlToolBoring_1] PRIMARY KEY REFERENCES TlToolDrill([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [TlRadiusType] INT, \r\n    [TaperAngle] DOUBLE, \r\n    [Shift] DOUBLE)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'TlRadiusType', type: 'INT' },
      { name: 'TaperAngle', type: 'DOUBLE' },
      { name: 'Shift', type: 'DOUBLE' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlToolBoring_1', columns: ['ID'] }],
  },
  {
    name: 'TlToolCenterDrill',
    sql: 'CREATE TABLE [TlToolCenterDrill](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlToolCenterDrill_1] PRIMARY KEY REFERENCES TlToolDrill([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [DrillLength] DOUBLE, \r\n    [DrillDiameter] DOUBLE)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'DrillLength', type: 'DOUBLE' },
      { name: 'DrillDiameter', type: 'DOUBLE' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlToolCenterDrill_1', columns: ['ID'] }],
  },
  {
    name: 'TlToolCounterBore',
    sql: 'CREATE TABLE [TlToolCounterBore](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlToolCounterBore_1] PRIMARY KEY REFERENCES TlToolDrill([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [PilotLength] DOUBLE, \r\n    [PilotDiameter] DOUBLE)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'PilotLength', type: 'DOUBLE' },
      { name: 'PilotDiameter', type: 'DOUBLE' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlToolCounterBore_1', columns: ['ID'] }],
  },
  {
    name: 'TlToolDrill',
    sql: 'CREATE TABLE [TlToolDrill](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlToolDrill_1] PRIMARY KEY NOT NULL REFERENCES TlToolMill([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [TipAngle] DOUBLE, \r\n    [ShoulderAngle] DOUBLE, \r\n    [CornerRadius] DOUBLE)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'TipAngle', type: 'DOUBLE' },
      { name: 'ShoulderAngle', type: 'DOUBLE' },
      { name: 'CornerRadius', type: 'DOUBLE' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlToolDrill_1', columns: ['ID'] }],
  },
  {
    name: 'TlToolEndmill',
    sql: 'CREATE TABLE [TlToolEndmill](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlToolEndmill_1] PRIMARY KEY NOT NULL REFERENCES TlToolMill([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [TipDiameter] DOUBLE, \r\n    [TaperAngle] DOUBLE, \r\n    [TlRadiusType] INT, \r\n    [CornerRadius] DOUBLE, \r\n    [ChamferLength] DOUBLE)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'TipDiameter', type: 'DOUBLE' },
      { name: 'TaperAngle', type: 'DOUBLE' },
      { name: 'TlRadiusType', type: 'INT' },
      { name: 'CornerRadius', type: 'DOUBLE' },
      { name: 'ChamferLength', type: 'DOUBLE' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlToolEndmill_1', columns: ['ID'] }],
  },
  {
    name: 'TlToolFeedMill',
    sql: 'CREATE TABLE [TlToolFeedMill](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlToolFeedMill_1] PRIMARY KEY REFERENCES TlToolMill([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [TipDiameter] DOUBLE, \r\n    [LowerRadius] DOUBLE, \r\n    [UpperRadius] DOUBLE, \r\n    [LowerTaperAngle] DOUBLE, \r\n    [UpperTaperAngle] DOUBLE, \r\n    [ReliefTaperAngle] DOUBLE)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'TipDiameter', type: 'DOUBLE' },
      { name: 'LowerRadius', type: 'DOUBLE' },
      { name: 'UpperRadius', type: 'DOUBLE' },
      { name: 'LowerTaperAngle', type: 'DOUBLE' },
      { name: 'UpperTaperAngle', type: 'DOUBLE' },
      { name: 'ReliefTaperAngle', type: 'DOUBLE' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlToolFeedMill_1', columns: ['ID'] }],
  },
  {
    name: 'TlToolGrade',
    sql: 'CREATE TABLE [TlToolGrade](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlToolGrade_1] PRIMARY KEY, \r\n    [ManufacturerID] GUID REFERENCES TlManufacturer([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [Name] VARCHAR, \r\n    [Description] VARCHAR)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'ManufacturerID', type: 'GUID' },
      { name: 'Name', type: 'VARCHAR' },
      { name: 'Description', type: 'VARCHAR' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlToolGrade_1', columns: ['ID'] }],
  },
  {
    name: 'TlToolGroup',
    sql: 'CREATE TABLE [TlToolGroup](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlToolGroup_1] PRIMARY KEY, \r\n    [Name] VARCHAR, \r\n    [Description] VARCHAR, \r\n    [ImagePath] VARCHAR, \r\n    [Image] BLOB)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'Name', type: 'VARCHAR' },
      { name: 'Description', type: 'VARCHAR' },
      { name: 'ImagePath', type: 'VARCHAR' },
      { name: 'Image', type: 'BLOB' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlToolGroup_1', columns: ['ID'] }],
  },
  {
    name: 'TlToolLathe',
    sql: 'CREATE TABLE [TlToolLathe](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlToolLathe_1] PRIMARY KEY NOT NULL REFERENCES TlTool([ID]), \r\n    [ToolClearanceAngle] FLOAT, \r\n    [ToolRakeAngle] FLOAT, \r\n    [ToolWidth] FLOAT, \r\n    [ToolHeight] FLOAT, \r\n    [HolderID] GUID REFERENCES TlHolderLathe([ID]), \r\n    [InsertID] GUID REFERENCES TlInsert([ID]), \r\n    [MachineSideConnectionType] INT, \r\n    [RequiresToolLocator] BOOL, ExternalId VARCHAR)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'ToolClearanceAngle', type: 'FLOAT' },
      { name: 'ToolRakeAngle', type: 'FLOAT' },
      { name: 'ToolWidth', type: 'FLOAT' },
      { name: 'ToolHeight', type: 'FLOAT' },
      { name: 'HolderID', type: 'GUID' },
      { name: 'InsertID', type: 'GUID' },
      { name: 'MachineSideConnectionType', type: 'INT' },
      { name: 'RequiresToolLocator', type: 'BOOL' },
      { name: 'ExternalId', type: 'VARCHAR' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlToolLathe_1', columns: ['ID'] }],
  },
  {
    name: 'TlToolLatheCustom',
    sql: 'CREATE TABLE [TlToolLatheCustom](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlToolLatheCustom_1] PRIMARY KEY NOT NULL REFERENCES TlToolLathe([ID]))',
    columns: [{ name: 'ID', type: 'GUID' }],
    indexes: [{ name: 'sqlite_autoindex_TlToolLatheCustom_1', columns: ['ID'] }],
  },
  {
    name: 'TlToolLatheISO',
    sql: 'CREATE TABLE [TlToolLatheISO](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlToolLatheISO_1] PRIMARY KEY NOT NULL REFERENCES TlToolLathe([ID]))',
    columns: [{ name: 'ID', type: 'GUID' }],
    indexes: [{ name: 'sqlite_autoindex_TlToolLatheISO_1', columns: ['ID'] }],
  },
  {
    name: 'TlToolMaterial',
    sql: 'CREATE TABLE [TlToolMaterial](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlToolMaterial_1] PRIMARY KEY REFERENCES TlMaterial([ID]))',
    columns: [{ name: 'ID', type: 'GUID' }],
    indexes: [{ name: 'sqlite_autoindex_TlToolMaterial_1', columns: ['ID'] }],
  },
  {
    name: 'TlToolMill',
    sql: 'CREATE TABLE [TlToolMill](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlToolMill_1] PRIMARY KEY NOT NULL REFERENCES TlTool([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [MCToolType] INT, \r\n    [DiameterOffsetNum] INT, \r\n    [LengthOffsetNum] INT, \r\n    [OverallLength] DOUBLE, \r\n    [ShoulderLength] DOUBLE, \r\n    [CuttingDepth] DOUBLE, \r\n    [OverallDiameter] DOUBLE, \r\n    [ArborDiameter] DOUBLE, \r\n    [ShoulderDiameter] DOUBLE, \r\n    [TlShankType] INT, \r\n    [TaperLength] DOUBLE, \r\n    [NeckDiameter] DOUBLE, \r\n    [FluteCount] INT, \r\n    [TlSpindleDir] INT, \r\n    [TlHelixType] INT, \r\n    [HelixAngle] DOUBLE, \r\n    [RequiredPilotDiameter] DOUBLE, \r\n    [IsVariablePitch] BOOL, \r\n    [IsScalable] BOOL, \r\n    [MfgToolCode] VARCHAR, \r\n    [Chuck] VARCHAR, \r\n    [ToolFileName] VARCHAR, \r\n    [TlGradeID] GUID REFERENCES TlToolGrade([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [TlOpParamsID] GUID REFERENCES TlOpParams([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [IsAcceleratedFinishing] BOOL)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'MCToolType', type: 'INT' },
      { name: 'DiameterOffsetNum', type: 'INT' },
      { name: 'LengthOffsetNum', type: 'INT' },
      { name: 'OverallLength', type: 'DOUBLE' },
      { name: 'ShoulderLength', type: 'DOUBLE' },
      { name: 'CuttingDepth', type: 'DOUBLE' },
      { name: 'OverallDiameter', type: 'DOUBLE' },
      { name: 'ArborDiameter', type: 'DOUBLE' },
      { name: 'ShoulderDiameter', type: 'DOUBLE' },
      { name: 'TlShankType', type: 'INT' },
      { name: 'TaperLength', type: 'DOUBLE' },
      { name: 'NeckDiameter', type: 'DOUBLE' },
      { name: 'FluteCount', type: 'INT' },
      { name: 'TlSpindleDir', type: 'INT' },
      { name: 'TlHelixType', type: 'INT' },
      { name: 'HelixAngle', type: 'DOUBLE' },
      { name: 'RequiredPilotDiameter', type: 'DOUBLE' },
      { name: 'IsVariablePitch', type: 'BOOL' },
      { name: 'IsScalable', type: 'BOOL' },
      { name: 'MfgToolCode', type: 'VARCHAR' },
      { name: 'Chuck', type: 'VARCHAR' },
      { name: 'ToolFileName', type: 'VARCHAR' },
      { name: 'TlGradeID', type: 'GUID' },
      { name: 'TlOpParamsID', type: 'GUID' },
      { name: 'IsAcceleratedFinishing', type: 'BOOL' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlToolMill_1', columns: ['ID'] }],
  },
  {
    name: 'TlToolReamer',
    sql: 'CREATE TABLE [TlToolReamer](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlToolReamer_1] PRIMARY KEY REFERENCES TlToolMill([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [TipAngle] DOUBLE, \r\n    [ChamferLength] DOUBLE)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'TipAngle', type: 'DOUBLE' },
      { name: 'ChamferLength', type: 'DOUBLE' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlToolReamer_1', columns: ['ID'] }],
  },
  {
    name: 'TlToolSlotMill',
    sql: 'CREATE TABLE [TlToolSlotMill](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlToolSlotMill_1] PRIMARY KEY REFERENCES TlToolEndmill([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [SecondaryRadiusType] INT, \r\n    [SecondaryCornerRadius] DOUBLE, \r\n    [SecondaryChamferDistance] DOUBLE, \r\n    [SecondaryChamferAngle] DOUBLE)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'SecondaryRadiusType', type: 'INT' },
      { name: 'SecondaryCornerRadius', type: 'DOUBLE' },
      { name: 'SecondaryChamferDistance', type: 'DOUBLE' },
      { name: 'SecondaryChamferAngle', type: 'DOUBLE' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlToolSlotMill_1', columns: ['ID'] }],
  },
  {
    name: 'TlToolThreading',
    sql: 'CREATE TABLE [TlToolThreading](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlToolThreading_1] PRIMARY KEY REFERENCES TlToolMill([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [TipDiameter] DOUBLE, \r\n    [TipAngle] DOUBLE, \r\n    [TlRadiusType] INT, \r\n    [CornerRadius] DOUBLE, \r\n    [ThreadPitch] DOUBLE, \r\n    [TlThreadShape] INT, \r\n    [RootDiameter] DOUBLE, \r\n    [ThreadAngle] DOUBLE, \r\n    [NStarts] INT)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'TipDiameter', type: 'DOUBLE' },
      { name: 'TipAngle', type: 'DOUBLE' },
      { name: 'TlRadiusType', type: 'INT' },
      { name: 'CornerRadius', type: 'DOUBLE' },
      { name: 'ThreadPitch', type: 'DOUBLE' },
      { name: 'TlThreadShape', type: 'INT' },
      { name: 'RootDiameter', type: 'DOUBLE' },
      { name: 'ThreadAngle', type: 'DOUBLE' },
      { name: 'NStarts', type: 'INT' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlToolThreading_1', columns: ['ID'] }],
  },
  {
    name: 'TlToolToTlOpType',
    sql: 'CREATE TABLE [TlToolToTlOpType](\r\n    [TlToolID] GUID REFERENCES TlTool([ID]) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED, \r\n    [TlOpTypeID] GUID REFERENCES TlOpType([ID]) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED, \r\n    CONSTRAINT [sqlite_autoindex_TlToolToTlOpType_1] PRIMARY KEY([TlToolID], [TlOpTypeID]))',
    columns: [
      { name: 'TlToolID', type: 'GUID' },
      { name: 'TlOpTypeID', type: 'GUID' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlToolToTlOpType_1', columns: ['TlToolID', 'TlOpTypeID'] }],
  },
  {
    name: 'TlToolType',
    sql: 'CREATE TABLE [TlToolType](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlToolType_1] PRIMARY KEY, \r\n    [Name] VARCHAR, \r\n    [Description] VARCHAR, \r\n    [ImagePath] VARCHAR, \r\n    [Image] BLOB, \r\n    [TlToolGroupID] GUID CONSTRAINT [sqlite_autoindex_TlToolType_1] REFERENCES TlToolGroup([ID]) DEFERRABLE INITIALLY DEFERRED)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'Name', type: 'VARCHAR' },
      { name: 'Description', type: 'VARCHAR' },
      { name: 'ImagePath', type: 'VARCHAR' },
      { name: 'Image', type: 'BLOB' },
      { name: 'TlToolGroupID', type: 'GUID' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlToolType_1', columns: ['ID'] }],
  },
  {
    name: 'TlTurnHolder',
    sql: 'CREATE TABLE [TlTurnHolder](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlTurnHolder_1] PRIMARY KEY NOT NULL REFERENCES TlAssemblyItem([ID]) DEFERRABLE INITIALLY DEFERRED, \r\n    [Type] INT,\r\n    [IsForYAxisCutting] BOOL)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'Type', type: 'INT' },
      { name: 'IsForYAxisCutting', type: 'BOOL' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlTurnHolder_1', columns: ['ID'] }],
  },
  {
    name: 'TlWorkMaterial',
    sql: 'CREATE TABLE [TlWorkMaterial](\r\n    [ID] GUID CONSTRAINT [sqlite_autoindex_TlWorkMaterial_1] PRIMARY KEY REFERENCES TlMaterial([ID]), \r\n    [ISOGroup] INT, \r\n    [Density] DOUBLE, \r\n    [HardnessUnit] INT, \r\n    [HardnessValue] DOUBLE)',
    columns: [
      { name: 'ID', type: 'GUID' },
      { name: 'ISOGroup', type: 'INT' },
      { name: 'Density', type: 'DOUBLE' },
      { name: 'HardnessUnit', type: 'INT' },
      { name: 'HardnessValue', type: 'DOUBLE' },
    ],
    indexes: [{ name: 'sqlite_autoindex_TlWorkMaterial_1', columns: ['ID'] }],
  },
  {
    name: '_Header',
    sql: 'CREATE TABLE [_Header](\r\n    [id] GUID CONSTRAINT [sqlite_autoindex__Header_1] PRIMARY KEY, \r\n    [version] INT, \r\n    [DataVersion] INT)',
    columns: [
      { name: 'id', type: 'GUID' },
      { name: 'version', type: 'INT' },
      { name: 'DataVersion', type: 'INT' },
    ],
    indexes: [{ name: 'sqlite_autoindex__Header_1', columns: ['id'] }],
  },
  {
    name: '_UpdateLog',
    sql: 'CREATE TABLE [_UpdateLog] (\r\n\t[Update] INT CONSTRAINT [sqlite_autoindex__UpdateLog_1] PRIMARY KEY,\r\n\t[Date] VARCHAR,\r\n\t[PreviousSchemaVersion] INT,\r\n\t[PreviousDataVersion] INT,\r\n\t[NewSchemaVersion] INT,\r\n\t[NewDataVersion] INT,\r\n\t[MCMajorVersion] INT,\r\n\t[MCMinorVersion] INT)',
    columns: [
      { name: 'Update', type: 'INT' },
      { name: 'Date', type: 'VARCHAR' },
      { name: 'PreviousSchemaVersion', type: 'INT' },
      { name: 'PreviousDataVersion', type: 'INT' },
      { name: 'NewSchemaVersion', type: 'INT' },
      { name: 'NewDataVersion', type: 'INT' },
      { name: 'MCMajorVersion', type: 'INT' },
      { name: 'MCMinorVersion', type: 'INT' },
    ],
    indexes: [{ name: 'sqlite_autoindex__UpdateLog_1', columns: ['Update'] }],
  },
]

/** The schema version this exporter writes, recorded in `_Header`. */
export const MASTERCAM_SCHEMA_VERSION = 32

/** The Mastercam release the schema was adopted from, as `_UpdateLog` states it. */
export const MASTERCAM_VERSION: readonly [major: number, minor: number] = [28, 230]

/**
 * The rows Mastercam ships in every library, under the guids it ships them
 * under.
 *
 * A tool that names a grade or a material names one of these. Minting our own
 * would produce a library whose tools belong to nothing.
 */
export const MASTERCAM_SEED: Readonly<Record<string, readonly Row[]>> = {
  TlManufacturer: [
    {
      Description: 'Mastercam Imported Data',
      ID: '096cfa82-ac35-4c73-939b-851df5fb539f',
      Name: 'Mastercam',
    },
  ],
  TlMaterial: [
    { Description: 'Carbide', ID: '7513e1e0-2e0c-407b-ad00-7e51ea9a429a', Name: 'Carbide' },
    { Description: 'HSS', ID: 'a2c64f46-6840-4969-8aee-da364cfe220c', Name: 'HSS' },
  ],
  TlOpGroup: [
    {
      Description: 'Milling Operation Group',
      ID: '497180c2-a6e4-11de-b80b-ffc956d89593',
      Image: null,
      ImagePath: null,
      Name: 'Milling',
    },
    {
      Description: 'Drilling Operation Group',
      ID: '5f97ab74-ba04-49ce-943c-47dc7ed9713a',
      Image: null,
      ImagePath: null,
      Name: 'Drilling',
    },
  ],
  TlOpType: [
    {
      Description: 'Surface',
      ID: '373cd3e8-766f-4e72-a306-e67e109ba201',
      Name: 'Surface',
      TlOpGroupID: '497180c2-a6e4-11de-b80b-ffc956d89593',
    },
    {
      Description: 'Facing',
      ID: '508c3916-a6e3-11de-bebd-bdc256d89593',
      Name: 'Facing',
      TlOpGroupID: '497180c2-a6e4-11de-b80b-ffc956d89593',
    },
    {
      Description: 'Drilling',
      ID: '61cabbc3-6787-4882-9e3c-fd326d1d85ac',
      Name: 'Drilling',
      TlOpGroupID: '5f97ab74-ba04-49ce-943c-47dc7ed9713a',
    },
    {
      Description: 'Shouldering',
      ID: '842a4e88-a6e4-11de-89ca-90cb56d89593',
      Name: 'Shouldering',
      TlOpGroupID: '497180c2-a6e4-11de-b80b-ffc956d89593',
    },
    {
      Description: 'Chamfering',
      ID: '9b310f54-a6e4-11de-9e9d-54cd56d89593',
      Name: 'Chamfering',
      TlOpGroupID: '497180c2-a6e4-11de-b80b-ffc956d89593',
    },
    {
      Description: 'Plunging',
      ID: 'a92f88e2-a6e4-11de-bee6-9bcd56d89593',
      Name: 'Plunging',
      TlOpGroupID: '497180c2-a6e4-11de-b80b-ffc956d89593',
    },
    {
      Description: 'Slotting',
      ID: 'b4ed2c34-a6e4-11de-a868-eacd56d89593',
      Name: 'Slotting',
      TlOpGroupID: '497180c2-a6e4-11de-b80b-ffc956d89593',
    },
    {
      Description: 'Profiling',
      ID: 'bec896bc-a6e4-11de-894f-25ce56d89593',
      Name: 'Profiling',
      TlOpGroupID: '497180c2-a6e4-11de-b80b-ffc956d89593',
    },
    {
      Description: 'Pocketing',
      ID: 'c2697dfa-ec58-408e-a708-8753601c17c6',
      Name: 'Pocketing',
      TlOpGroupID: '497180c2-a6e4-11de-b80b-ffc956d89593',
    },
    {
      Description: 'Contouring',
      ID: 'e0d8a947-0905-43e9-8e01-80334ffb6a29',
      Name: 'Contouring',
      TlOpGroupID: '497180c2-a6e4-11de-b80b-ffc956d89593',
    },
  ],
  TlToolGrade: [
    {
      Description: 'Mastercam Imported Data',
      ID: 'f9c5c3cc-570b-410d-a827-8dab6bbf50e1',
      ManufacturerID: '096cfa82-ac35-4c73-939b-851df5fb539f',
      Name: 'Mastercam Default Grade',
    },
  ],
  TlToolGroup: [
    {
      Description: 'Legacy Mastercam Tool Types',
      ID: '04ccb858-e154-432d-ab5a-3f2967709509',
      Image: null,
      ImagePath: '',
      Name: 'Mastercam Tool Types',
    },
  ],
  TlToolMaterial: [
    { ID: '7513e1e0-2e0c-407b-ad00-7e51ea9a429a' },
    { ID: 'a2c64f46-6840-4969-8aee-da364cfe220c' },
  ],
  TlToolType: [
    {
      Description: 'Legacy Block Drill tool type',
      ID: '14677698-7230-4efd-9cd9-e22908e604a8',
      Image: null,
      ImagePath: '',
      Name: 'Block Drill',
      TlToolGroupID: '04ccb858-e154-432d-ab5a-3f2967709509',
    },
    {
      Description: 'Legacy Cbore tool type',
      ID: '234e3daf-2c37-4156-895d-cfd36b2ccbd8',
      Image: null,
      ImagePath: '',
      Name: 'CBore',
      TlToolGroupID: '04ccb858-e154-432d-ab5a-3f2967709509',
    },
    {
      Description: 'Legacy Endmill3 Bull tool type',
      ID: '2ffbf697-4e0c-4d38-a0f3-15f70ec87d7f',
      Image: null,
      ImagePath: '',
      Name: 'Endmill3 Bull',
      TlToolGroupID: '04ccb858-e154-432d-ab5a-3f2967709509',
    },
    {
      Description: 'Legacy Engrave tool type',
      ID: '31a0e201-5681-4c1d-b968-e8c72c3ff9c8',
      Image: null,
      ImagePath: '',
      Name: 'Engrave Tool',
      TlToolGroupID: '04ccb858-e154-432d-ab5a-3f2967709509',
    },
    {
      Description: 'Legacy Reamer tool type',
      ID: '3bdfee85-a9f2-46d3-9cde-fd05afa07f39',
      Image: null,
      ImagePath: '',
      Name: 'Reamer',
      TlToolGroupID: '04ccb858-e154-432d-ab5a-3f2967709509',
    },
    {
      Description: 'Legacy Chamfer Mill tool type',
      ID: '47cf2b08-e825-4d65-9d5a-d06621a2b905',
      Image: null,
      ImagePath: '',
      Name: 'Chamfer Mill',
      TlToolGroupID: '04ccb858-e154-432d-ab5a-3f2967709509',
    },
    {
      Description: 'Legacy Bore tool type',
      ID: '5085dc58-3d09-4aa0-a829-ad0fb8f59a66',
      Image: null,
      ImagePath: '',
      Name: 'Bore',
      TlToolGroupID: '04ccb858-e154-432d-ab5a-3f2967709509',
    },
    {
      Description: 'Legacy Spot Drill tool type',
      ID: '510b5c09-dc27-43ff-bd3f-4d63a4c65c0a',
      Image: null,
      ImagePath: '',
      Name: 'Spot Drill',
      TlToolGroupID: '04ccb858-e154-432d-ab5a-3f2967709509',
    },
    {
      Description: 'Legacy Undefined tool type',
      ID: '57ec84cd-b5aa-4f74-b1a2-6c479e5662fc',
      Image: null,
      ImagePath: '',
      Name: 'Undefined',
      TlToolGroupID: '04ccb858-e154-432d-ab5a-3f2967709509',
    },
    {
      Description: 'Legacy Lollipop Mill tool type',
      ID: '77636c16-1b47-4327-999a-d6ba2aaf5784',
      Image: null,
      ImagePath: '',
      Name: 'Lollipop Mill',
      TlToolGroupID: '04ccb858-e154-432d-ab5a-3f2967709509',
    },
    {
      Description: 'Legacy Dove Mill tool type',
      ID: '776bc9ab-4812-4fe1-97f8-d6ff9bf69741',
      Image: null,
      ImagePath: '',
      Name: 'Dove Mill',
      TlToolGroupID: '04ccb858-e154-432d-ab5a-3f2967709509',
    },
    {
      Description: 'Legacy Center Drill tool type',
      ID: '781adb72-a2ee-4bd7-99d6-978fae9801f9',
      Image: null,
      ImagePath: '',
      Name: 'Center Drill',
      TlToolGroupID: '04ccb858-e154-432d-ab5a-3f2967709509',
    },
    {
      Description: 'Legacy Endmill2 Sphere tool type',
      ID: '8d4e7905-bf6c-438e-8cb9-d7fb40c97497',
      Image: null,
      ImagePath: '',
      Name: 'Endmill2 Sphere',
      TlToolGroupID: '04ccb858-e154-432d-ab5a-3f2967709509',
    },
    {
      Description: 'Legacy Drill tool type',
      ID: '98c2be7e-c806-4b6e-acaa-067e97d29086',
      Image: null,
      ImagePath: '',
      Name: 'Drill',
      TlToolGroupID: '04ccb858-e154-432d-ab5a-3f2967709509',
    },
    {
      Description: 'Legacy radius Mill tool type',
      ID: 'a29381b2-91e5-4d15-ba71-f80e17d5c4e5',
      Image: null,
      ImagePath: '',
      Name: 'Radius Mill',
      TlToolGroupID: '04ccb858-e154-432d-ab5a-3f2967709509',
    },
    {
      Description: 'Legacy Bradpt Drill tool type',
      ID: 'be99d343-550a-444f-b84e-774c629634e0',
      Image: null,
      ImagePath: '',
      Name: 'Bradpt Drill',
      TlToolGroupID: '04ccb858-e154-432d-ab5a-3f2967709509',
    },
    {
      Description: 'Legacy Slot Mill tool type',
      ID: 'c3c71c0c-3545-4a72-af76-d7272a5a7e17',
      Image: null,
      ImagePath: '',
      Name: 'Slot Mill',
      TlToolGroupID: '04ccb858-e154-432d-ab5a-3f2967709509',
    },
    {
      Description: 'Legacy Endmill1 Flat tool type',
      ID: 'caf7acba-4bc0-4841-a2d8-17a9529ce42f',
      Image: null,
      ImagePath: '',
      Name: 'Endmill1 Flat',
      TlToolGroupID: '04ccb858-e154-432d-ab5a-3f2967709509',
    },
    {
      Description: 'Legacy Csink tool type',
      ID: 'e8c3a113-2748-43a8-9950-d90b8e864363',
      Image: null,
      ImagePath: '',
      Name: 'Csink',
      TlToolGroupID: '04ccb858-e154-432d-ab5a-3f2967709509',
    },
    {
      Description: 'Legacy Taper Mill tool type',
      ID: 'e9d80248-76df-4ca9-b154-83f4eef1b1e7',
      Image: null,
      ImagePath: '',
      Name: 'Taper Mill',
      TlToolGroupID: '04ccb858-e154-432d-ab5a-3f2967709509',
    },
  ],
}
