/**
 * Record identity: one guid space per vendor, and what shares it.
 *
 * A guid is the join key for every downstream consumer of a scrape, so what
 * these pin is not arithmetic — it is that the arithmetic never moves.
 *
 * ## Why this file carries literal UUIDs where the Python did not
 *
 * The Python suite could assert `record_guid('widia', …)` against
 * `uuid.uuid5(uuid.uuid5(NAMESPACE_URL, home), …)` computed inline, because
 * `uuid5` was the standard library's and testing it would have been testing
 * CPython. Here it is eleven lines in `src/uuid5.ts`, so an inline
 * recomputation would check the guid against the same code that produced it
 * and pass on any consistent mistake.
 *
 * **Every literal below was generated by the Python this package replaces.**
 * They are the port's acceptance test: a catalog built from a scrape run last
 * month has to still match one scraped by this code today.
 */

import { describe, expect, it } from 'vitest'

import {
  AEM_BRANDS,
  BRANDS,
  productLink,
  recordGuid,
  vendorNamespace,
  type BrandName,
} from '../src/identity.js'
import { NAMESPACE_URL, uuid5 } from '../src/uuid5.js'

/**
 * The single namespace this package minted every record under before
 * 2026-08-07, spelled out rather than derived. Kennametal's per-vendor
 * namespace has to equal it, or the migration to per-vendor namespaces churned
 * 793 Kennametal guids as well as the six WIDIA ones — and every stored cart
 * line, bookmark and saved order that named one would have gone stale.
 */
const HISTORICAL_NAMESPACE = 'f286e243-6a92-5213-bef8-132df4e74180'

describe('uuid5 agrees with Python', () => {
  // Generated with `uuid.uuid5(uuid.NAMESPACE_URL, …)` under CPython 3.11.
  it.each([
    ['https://www.kennametal.com', 'f286e243-6a92-5213-bef8-132df4e74180'],
    ['https://www.widia.com', '71ac177f-0cb1-588a-831d-05aef69c3582'],
    ['https://us.rego-fix.com', '5010adc0-c74b-5f03-9a84-2e0a610c6d7a'],
    ['https://destinytool.com', '17da919d-5492-55ea-907f-7802692d900f'],
  ])('mints %s', (name, expected) => {
    expect(uuid5(NAMESPACE_URL, name)).toBe(expected)
  })

  it('encodes the name as UTF-8, not as code units', () => {
    // The one case where a plausible implementation silently diverges: a name
    // outside ASCII hashed as UTF-16 or latin-1 produces a well-formed UUID
    // that is simply not the one Python minted.
    expect(uuid5(HISTORICAL_NAMESPACE, 'Ø10-Ünïcode')).toBe('7d37ff6a-8c3e-5822-a417-157137741994')
  })

  it('accepts the empty name, because a lost column mints one', () => {
    // Not hypothetical: `check_identity_columns` exists because a re-scrape
    // whose part-number column was renamed mints every guid off ''. This pins
    // what that produces, so the symptom is recognisable rather than novel.
    expect(uuid5(HISTORICAL_NAMESPACE, '')).toBe('9eda27c0-c1fa-5efb-8f18-19f46b27fd90')
  })
})

describe('vendor namespaces', () => {
  it('leaves Kennametal guids unchanged by the move to per-vendor namespaces', () => {
    expect(vendorNamespace('kennametal')).toBe(HISTORICAL_NAMESPACE)
  })

  it('gives every brand its own', () => {
    const namespaces = Object.keys(BRANDS).map((brand) => vendorNamespace(brand as BrandName))
    expect(new Set(namespaces).size).toBe(Object.keys(BRANDS).length)
  })
})

describe('record guids', () => {
  it('did not move a single guid in the port', () => {
    // The whole point of copying `BRANDS` verbatim rather than deriving `home`
    // from `host`. Both values come from the Python package.
    expect(recordGuid('widia', '5872291')).toBe('d07b74bc-8436-524e-8dfc-81dcce91fe05')
    expect(recordGuid('regofix', '2130.70610')).toBe('738e3c80-af4a-56d9-aab7-c08bd7bfa48a')
  })

  it('does not collide when two vendors share a material number', () => {
    // The failure this prevents: a material number is a vendor-local integer,
    // and nothing reserves one to Kennametal. Under a single namespace the two
    // records below were the same guid, and the second silently shadowed the
    // first in every lookup a catalog builds.
    expect(recordGuid('kennametal', '100003658')).toBe('5f5c06ff-c41f-5b1b-b4c9-422e13df8591')
    expect(recordGuid('widia', '100003658')).toBe('57140db2-cdf3-590b-8d4a-3410133669fe')
    expect(recordGuid('kennametal', '100003658')).not.toBe(recordGuid('widia', '100003658'))
  })

  it('is stable across calls', () => {
    expect(recordGuid('widia', '5872291')).toBe(recordGuid('widia', '5872291'))
  })

  it('refuses an unknown brand at compile time', () => {
    // The Python raised `KeyError` here, and the reason it needed a test was
    // that a typo'd brand which minted a namespace anyway would produce guids
    // no re-run reproduces. `BrandName` is derived from `BRANDS`, so the same
    // guarantee now holds before the code runs — this asserts the type error
    // exists, which is the only way it can regress silently.
    // @ts-expect-error 'sandvik' is not a brand this package knows
    expect(() => vendorNamespace('sandvik')).toBeTypeOf('function')
  })
})

describe('product links', () => {
  it('is per brand, because the shape is not shared', () => {
    // One format string with a `{host}` hole encoded the AEM product path as
    // though it were universal. Two of the four brands publish no per-part
    // page at all, and linking a search is the honest answer rather than a 404.
    expect(productLink('kennametal', '4151623')).toBe(
      'https://www.kennametal.com/us/en/products/p.4151623.html',
    )
    expect(productLink('regofix', '2130.70610')).toBe(
      'https://us.rego-fix.com/en/productfinder?q=2130.70610',
    )
    expect(productLink('destinytool', 'BC208031D')).toBe(
      'https://destinytool.com/products/BC208031D',
    )
  })
})

describe('the brand table', () => {
  it('carries what identity reads off every brand', () => {
    for (const [brand, cfg] of Object.entries(BRANDS)) {
      expect(cfg.home, brand).toMatch(/^https:\/\//)
      expect(cfg.productLink, brand).toContain('{material}')
      expect(cfg.vendor, brand).not.toBe('')
      expect(cfg.host, brand).not.toBe('')
    }
  })

  it('carries an AEM node on exactly the two AEM brands', () => {
    // `node` is deliberately absent from two of them — it names an AEM
    // component, which is a fact about Kennametal's platform and not about
    // vendors in general.
    const withNode = Object.entries(BRANDS)
      .filter(([, cfg]) => 'node' in cfg)
      .map(([brand]) => brand)

    expect(new Set(withNode)).toEqual(new Set(['kennametal', 'widia']))
    // And `AEM_BRANDS` — which `AemBrandName` is derived from — says the same
    // two, so the list a caller is checked against cannot drift from the type.
    expect([...AEM_BRANDS].sort()).toEqual(['kennametal', 'widia'])
  })
})
