/**
 * Thread designations in, native-unit numbers out.
 *
 * A thread designation is a *standard* — `#2-56` is a UTS thread and `M6X1` an
 * ISO metric one whoever prints it — so these are domain arithmetic, not a
 * vendor's table. The named cases below are the designations actually seen in
 * the scraped tables, spacing variants included, because the spacing is where
 * this last broke.
 *
 * `fixtures/thread-vectors.json` is the port's own gate: 2,232 designations
 * covering machine screw numbers 0–14, the thirteen fractional sizes and
 * twenty metric sizes against every threads-per-inch value from 4 to 80,
 * generated by running the Python this replaces. It is what turns "the
 * rounding should agree" into a checked claim — including the asymmetry that a
 * lowercase `M6x1` parses for pitch and is refused for major diameter, which
 * no reader would think to write a case for.
 */

import { describe, expect, it } from 'vitest'

import { threadMajorDiameter, threadPitch, type ThreadSystem } from '../src/thread.js'
import vectors from './fixtures/thread-vectors.json' with { type: 'json' }

describe('metric major diameter', () => {
  it.each([
    ['M2X0.4', 2.0],
    ['M12X1.75', 12.0],
    ['M30X3.5', 30.0],
  ])('reads %s', (tdz, expected) => {
    expect(threadMajorDiameter(tdz, 'metric')).toBe(expected)
  })
})

describe('inch major diameter', () => {
  it.each([
    ['#0-80', 0.06],
    ['#0 - 80', 0.06], // space variant seen in scrape
    ['#2-56', 0.086],
    ['#10-32', 0.19],
    ['#12-24', 0.216],
    ['1/4-20', 0.25],
    ['1/4 - 20', 0.25],
    ['5/16-18', 0.3125],
    ['3/4 - 10', 0.75],
  ])('reads %s', (tdz, expected) => {
    expect(threadMajorDiameter(tdz, 'inch')).toBeCloseTo(expected, 10)
  })

  it('takes machine screw numbers from the ANSI formula', () => {
    // `0.060 + 0.013 * N` inches, not a lookup table — which is why `#12`
    // works without anybody having entered it.
    expect(threadMajorDiameter('#12-24', 'inch')).toBeCloseTo(0.06 + 0.013 * 12, 10)
  })

  it.each([
    ['garbage', 'inch'],
    ['M2', 'metric'], // no pitch: not a designation
    ['2-56', 'inch'], // no `#`: not a machine-screw number
    ['#abc-40', 'inch'], // a `#` with no number behind it
    ['1/-20', 'inch'], // a fraction with no denominator
  ] as [string, ThreadSystem][])('refuses %s', (tdz, system) => {
    // The last two used to fall through to arithmetic on NaN and hand back a
    // diameter of NaN, where every other unreadable shape here throws.
    expect(() => threadMajorDiameter(tdz, system)).toThrow(RangeError)
  })
})

describe('pitch', () => {
  it.each([
    ['M6X1', 'metric', '1'],
    ['M12X1.75', 'metric', '1.75'],
    ['#4-40', 'inch', '0.025'],
    ['1/4 - 20', 'inch', '0.05'],
  ] as [string, ThreadSystem, string][])(
    'returns %s in its native unit',
    (designation, system, expected) => {
      // Millimetres on a metric thread, `1/TPI` inches on an inch one. The two
      // are read from one CSV column, which is only sound because the value is
      // already in the tap's own system when it is written.
      expect(threadPitch(designation, system)).toBe(expected)
    },
  )

  it('is the string that goes into the CSV', () => {
    // So re-running the step is a no-op rather than a float round-trip that
    // rewrites `1` as `1.0` in every row.
    expect(threadPitch('M6X1', 'metric')).toBeTypeOf('string')
    expect(threadPitch('M6X1', 'metric')).toBe('1')
  })

  it.each([
    ['M6', 'metric'],
    ['#4', 'inch'],
    ['M6X1', 'inch'], // right designation, wrong system
  ] as [string, ThreadSystem][])('refuses %s', (designation, system) => {
    // Rather than defaulting. A tap shipped with a guessed pitch is a tap that
    // cuts the wrong thread.
    expect(() => threadPitch(designation, system)).toThrow(RangeError)
  })
})

describe('agreement with the Python this replaces', () => {
  it(`reproduces ${vectors.major.length} major diameters exactly`, () => {
    const wrong = (vectors.major as [string, ThreadSystem, number][]).filter(
      ([tdz, system, expected]) => threadMajorDiameter(tdz, system) !== expected,
    )
    expect(wrong).toEqual([])
  })

  it(`reproduces ${vectors.pitch.length} pitches exactly, as strings`, () => {
    // Strings, not numbers: the CSV cell is what has to match, and `1` vs
    // `1.0` is the difference between a no-op re-run and a rewritten column.
    const wrong = (vectors.pitch as [string, ThreadSystem, string][]).filter(
      ([designation, system, expected]) => threadPitch(designation, system) !== expected,
    )
    expect(wrong).toEqual([])
  })
})
