/**
 * Thread designations in, native-unit numbers out.
 *
 * **Core, not an adapter**, and the distinction is the one this package draws
 * everywhere: a thread designation is a *standard* — `#2-56` is a UTS thread
 * and `M6 X 1` an ISO metric one whoever prints it — so parsing one is domain
 * arithmetic that every vendor's taps need and none of them owns. What is
 * Kennametal's is that its tables publish the designation in a column called
 * `D1-TDZ` and publish no pitch at all, and that fact lives in
 * `vendors/kennametal/thread-column.ts` with the CSV step that fixes it.
 *
 * Native units throughout — millimetres for metric threads, inches for inch
 * threads. A tap's system is a per-row fact, so the caller passes it in rather
 * than this module assuming a family's.
 *
 * ## Rounding is pinned, not incidental
 *
 * Python's `round` is half-to-even over a float; JavaScript has no direct
 * equivalent. Both functions below round the way the Python did, and
 * `tests/thread.test.ts` checks all 2,232 designations this package can
 * plausibly meet against output generated by it. Within the ranges that occur
 * — machine screw numbers 0–14, 4 to 80 threads per inch — no value lands on
 * an exact half, so `Math.round` and half-to-even cannot disagree; the vectors
 * are what makes that a checked fact rather than an argument.
 */

/** Which standard a designation is written in, and therefore its unit. */
export type ThreadSystem = 'metric' | 'inch'

/** `M10X1.5` — the capital `X` is required, as the Python's pattern was. */
const METRIC_MAJOR = /^M([0-9]+(?:\.[0-9]+)?)X[0-9.]+$/

/** `M6 x 1`, `M6X1` — pitch parsing accepts either case, major diameter does not. */
const METRIC_PITCH = /[xX]\s*([\d.]+)\s*$/

/** `#4-40`, `1/4 - 20` — the trailing number is threads per inch. */
const INCH_PITCH = /-\s*([\d.]+)\s*$/

/** Round to `places` decimals the way Python's `round(x, places)` does here. */
function round(value: number, places: number): number {
  const scale = 10 ** places
  return Math.round(value * scale) / scale
}

/**
 * Major diameter from a thread designation string, in the thread system's
 * native unit (mm for metric, inches for inch).
 *
 * Formats seen in the scraped tables: `M10X1.5`, `#2-56`, `#0 - 80`,
 * `1/4 - 20`, `5/16-18`.
 */
export function threadMajorDiameter(tdz: string, threadSystem: ThreadSystem): number {
  const s = tdz.replaceAll(' ', '')

  if (threadSystem === 'metric') {
    const match = METRIC_MAJOR.exec(s)
    if (!match?.[1]) {
      throw new RangeError(`unrecognized metric thread designation: ${tdz}`)
    }
    return Number(match[1])
  }

  const size = s.split('-', 1)[0] ?? ''
  if (size.startsWith('#')) {
    // ANSI machine-screw numbers: major dia = 0.060 + 0.013 * N inches
    const n = Number.parseInt(size.slice(1), 10)
    if (!Number.isInteger(n)) {
      throw new RangeError(`unrecognized inch thread designation: ${tdz}`)
    }
    return round(0.06 + 0.013 * n, 4)
  }
  if (size.includes('/')) {
    const [num, den] = size.split('/')
    const value = Number(num) / Number(den)
    // A designation like `1/` parses to NaN, which would otherwise travel into
    // a record as a diameter. Every other unreadable shape here throws.
    if (!Number.isFinite(value)) {
      throw new RangeError(`unrecognized inch thread designation: ${tdz}`)
    }
    return value
  }
  throw new RangeError(`unrecognized inch thread designation: ${tdz}`)
}

/**
 * Pitch from a thread designation, in the thread system's native unit.
 *
 * ```
 * metric: 'M6X1'     -> '1'        (mm, the value after the X)
 * inch:   '#4-40'    -> '0.025'    (in, 1 / threads-per-inch)
 *         '1/4 - 20' -> '0.05'
 * ```
 *
 * Returned as the string that goes into the CSV, so re-running the step is a
 * no-op rather than a float round-trip that rewrites `1` as `1.0` in every row.
 */
export function threadPitch(designation: string, threadSystem: ThreadSystem): string {
  if (threadSystem === 'metric') {
    const match = METRIC_PITCH.exec(designation)
    if (match?.[1]) return match[1]
  } else {
    const match = INCH_PITCH.exec(designation)
    if (match?.[1]) return String(round(1 / Number(match[1]), 6))
  }
  throw new RangeError(`cannot parse pitch from ${designation} (${threadSystem})`)
}
