/**
 * RFC 4122 name-based UUIDs, version 5.
 *
 * Python's `uuid` module ships this; Node's does not — `node:crypto` offers
 * `randomUUID` and nothing else — so the eleven lines are here rather than as
 * a dependency. It is SHA-1 over the namespace's 16 bytes followed by the
 * name's UTF-8 bytes, truncated to 16, with the version and variant bits
 * overwritten.
 *
 * **This has to agree with Python's `uuid.uuid5` byte for byte.** Tool guids
 * are the join key every downstream consumer of a scrape uses, so a value that
 * differs by one bit is not a formatting difference, it is a catalog that no
 * longer matches the one scraped last month. `tests/identity.test.ts` pins the
 * output against values generated by the Python this was ported from, for the
 * ordinary case and for the two that would catch an encoding slip — a name
 * with non-ASCII in it, and the empty name.
 */

import { createHash } from 'node:crypto'

/**
 * RFC 4122's namespace for URLs.
 *
 * The only namespace this package seeds from: every brand's namespace is
 * itself a v5 UUID of that brand's home page under this one.
 */
export const NAMESPACE_URL = '6ba7b811-9dad-11d1-80b4-00c04fd430c8'

/** The 16 bytes a hyphenated UUID string denotes. */
function bytesOf(uuid: string): Buffer {
  const hex = uuid.replaceAll('-', '')
  if (hex.length !== 32 || !/^[0-9a-fA-F]{32}$/.test(hex)) {
    throw new TypeError(`not a UUID: ${uuid}`)
  }
  return Buffer.from(hex, 'hex')
}

/** The canonical 8-4-4-4-12 rendering of 16 bytes. */
function format(bytes: Buffer): string {
  const hex = bytes.toString('hex')
  return [
    hex.slice(0, 8),
    hex.slice(8, 12),
    hex.slice(12, 16),
    hex.slice(16, 20),
    hex.slice(20, 32),
  ].join('-')
}

/**
 * The version 5 UUID of `name` within `namespace`.
 *
 * Deterministic across machines and runs, which is the whole point — see the
 * module docstring.
 */
export function uuid5(namespace: string, name: string): string {
  const digest = createHash('sha1')
    .update(bytesOf(namespace))
    .update(Buffer.from(name, 'utf8'))
    .digest()

  const bytes = digest.subarray(0, 16)
  // Version 5 in the high nibble of octet 6, and the RFC 4122 variant in the
  // top two bits of octet 8. `writeUInt8`/`readUInt8` rather than index
  // assignment so the arithmetic is on `number` and not on `number |
  // undefined` under `noUncheckedIndexedAccess`.
  bytes.writeUInt8((bytes.readUInt8(6) & 0x0f) | 0x50, 6)
  bytes.writeUInt8((bytes.readUInt8(8) & 0x3f) | 0x80, 8)
  return format(bytes)
}
